### ISSUE TITLE
Should SuccessExitStatus=2 be SuccessExitStatus=0,2?

### ISSUE THREAD

**Issue by alkisg** [fwupd/fwupd#4567] opened 2022-04-28 08:11 UTC
Hi, I noticed that fwupd-refresh is in failed state in all my Ubuntu 20.04 and 22.04 installations.

```
 fwupd-refresh.service - Refresh fwupd metadata and update motd
     Loaded: loaded (/lib/systemd/system/fwupd-refresh.service; static)
     Active: failed (Result: exit-code) since Thu 2022-04-28 10:14:32 EEST; 56min ago
TriggeredBy: * fwupd-refresh.timer
       Docs: man:fwupdmgr(1)
    Process: 193248 ExecStart=/usr/bin/fwupdmgr refresh (code=exited, status=1/FAILURE)
   Main PID: 193248 (code=exited, status=1/FAILURE)
        CPU: 34ms

Apr 28 10:14:32 alkis systemd[1]: Starting Refresh fwupd metadata and update motd...
Apr 28 10:14:32 alkis systemd[1]: fwupd-refresh.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 10:14:32 alkis systemd[1]: fwupd-refresh.service: Failed with result 'exit-code'.
Apr 28 10:14:32 alkis systemd[1]: Failed to start Refresh fwupd metadata and update motd.
```

Reading its man page, I see:

> Commands  that successfully execute will return "0", but commands that have no actions but successfully execute will return "2".

If both of them are "successful", shouldn't then `SuccessExitStatus=2` be `SuccessExitStatus=0,2` in ./data/motd/fwupd-refresh.service.in?

By applying that change, the unit is no longer in a failed state.

**Comment by superm1** [comment] 2022-04-28 13:11
The is a duplicate of https://github.com/fwupd/fwupd/issues/3037.  IOW the issue you're seeing is https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1969976

**Closed by superm1** 2022-04-28 13:11 UTC
Labels: duplicate, question
