### ISSUE TITLE
Dell WD19TB upgrade issue

### ISSUE THREAD

**Issue by sitnik** [fwupd/fwupd#2185] opened 2020-06-16 08:11 UTC
**Describe the bug**
I've tried to install 01.00.14.01 update on WD19TB but it reverts after powering off the dock.

**Steps to Reproduce**
1. Enable lvfs-testing:
```shell
$ sudo fwupdmgr enable-remote lvfs-testing
╔══════════════════════════════════════════════════════════════════════════════╗
║ The LVFS is a free service that operates as an independent legal entity and  ║
║ has no connection with Debian GNU/Linux. Your distributor may not have       ║
║ verified any of the firmware updates for compatibility with your system or   ║
║ connected devices. All firmware is provided only by the original equipment   ║
║ manufacturer.                                                                ║
║                                                                              ║
║ This remote contains firmware which is not embargoed, but is still being     ║
║ tested by the hardware vendor. You should ensure you have a way to manually  ║
║ downgrade the firmware if the firmware update fails.                         ║
║                                                                              ║
║ Enabling this functionality is done at your own risk, which means you have   ║
║ to contact your original equipment manufacturer regarding any problems       ║
║ caused by these updates. Only problems with the update process itself        ║
║ should be filed at https://bugs.debian.org/.                                 ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

Agree and enable the remote? [Y|n]: y
Successfully enabled remote
```
2. Check for available updates:
```shell
$ sudo fwupdmgr get-updates
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version
Latitude 5491
│
├─Package level of Dell dock:
│ │   Device ID:           b5a854df85ab30fff48e4365ec7ad2249c90806e
│ │   Summary:             A representation of dock update status
│ │   Current version:     01.00.14.00
│ │   Vendor:              Dell Inc. (USB:0x413C)
│ │   Install Duration:    5 seconds
│ │   GUID:                8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
│ │   Device Flags:        • Updatable
│ │                        • Supported on remote server
│ │                        • Device can recover flash failures
│ │                        • Device is usable for the duration of the update
│ │
│ └─WD19/WD19DC/WDTB Device Update:
│       New version:       01.00.14.01
│       Remote ID:         lvfs-testing
│       Summary:           Update package for the WD19 family
│       License:           Proprietary
│       Size:              24 bytes
│       Details:           https://www.dell.com/support/article/sln320770/
│       Vendor:            Dell Inc.
│       Duration:          5 seconds
│       Flags:             is-upgrade
│       Description:       -Addressed rare video/display issues related to isolated combinations of host PCs, discrete GPUs and monitors.
│
│       -Improved the compatibility of the Dock firmware update utility.
│
│       -Updated firmware to comply with Apple certification requirements, which is applicable to the Dell Thunderbolt Dock - WD19TB only. Note that WD19TB is not fully compatible with Apple USB-C hosts.
│
└─WD19TB:
  │   Device ID:           570867f4ddda9915445da59bd85cd0e0e507270e
  │   Summary:             High performance dock
  │   Current version:     01.00.00.00
  │   Minimum Version:     01.00.00.00
  │   Vendor:              Dell Inc. (USB:0x413C)
  │   Install Duration:    1 minute
  │   Serial Number:       DG6QGX2/3146033589114229
  │   GUID:                cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
  │   Device Flags:        • Updatable
  │                        • Requires AC power
  │                        • Supported on remote server
  │                        • Device update needs activation
  │                        • Device stages updates
  │                        • Device can recover flash failures
  │                        • Device is usable for the duration of the update
  │
  └─ Embedded Controller Update:
        New version:       01.00.00.04
        Remote ID:         lvfs-testing
        Summary:           Update for the Embedded controller within a Dell dock
        License:           Proprietary
        Size:              131.0 kB
        Vendor:            Dell Inc.
        Duration:          1 minute
        Flags:             is-upgrade
        Description:       Updated version to 01.00.00.04.
```
3. Install a new version
```shell
$ sudo fwupdmgr upgrade
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
Upgrade available for Package level of Dell dock from 01.00.14.00 to 01.00.14.01
Downloading 01.00.14.01 for Package level of Dell dock...
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Updating Package level of Dell dock…                             ]
Restarting device…       [***************************************]
Updating WD19TB…         [  -                                    ]
Writing…                 [***************************************]
Updating Package level of Dell dock…
Idle…                    [***************************************]
Updating WD19TB…
Idle…                    [***************************************]
Successfully installed firmware
Upload message: 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive; 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive
Successfully uploaded 1 report
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• WD19TB has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version
```
4. Check for available updates right after the installation:
```shell
$ sudo fwupdmgr get-updates
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
• Package level of Dell dock has the latest available firmware version
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• WD19TB has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version
```
Nothing is here

5. Power cycle the dock
6. Check for available updates again:
```shell
$ sudo fwupdmgr get-updates
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version
Latitude 5491
│
├─Package level of Dell dock:
│ │   Device ID:           b5a854df85ab30fff48e4365ec7ad2249c90806e
│ │   Summary:             A representation of dock update status
│ │   Current version:     01.00.14.00
│ │   Vendor:              Dell Inc. (USB:0x413C)
│ │   Install Duration:    5 seconds
│ │   GUID:                8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
│ │   Device Flags:        • Updatable
│ │                        • Supported on remote server
│ │                        • Device can recover flash failures
│ │                        • Device is usable for the duration of the update
│ │
│ └─WD19/WD19DC/WDTB Device Update:
│       New version:       01.00.14.01
│       Remote ID:         lvfs-testing
│       Summary:           Update package for the WD19 family
│       License:           Proprietary
│       Size:              24 bytes
│       Details:           https://www.dell.com/support/article/sln320770/
│       Vendor:            Dell Inc.
│       Duration:          5 seconds
│       Flags:             is-upgrade
│       Description:       -Addressed rare video/display issues related to isolated combinations of host PCs, discrete GPUs and monitors.
│
│       -Improved the compatibility of the Dock firmware update utility.
│
│       -Updated firmware to comply with Apple certification requirements, which is applicable to the Dell Thunderbolt Dock - WD19TB only. Note that WD19TB is not fully compatible with Apple USB-C hosts.
│
└─WD19TB:
  │   Device ID:           570867f4ddda9915445da59bd85cd0e0e507270e
  │   Summary:             High performance dock
  │   Current version:     01.00.00.00
  │   Minimum Version:     01.00.00.00
  │   Vendor:              Dell Inc. (USB:0x413C)
  │   Install Duration:    1 minute
  │   Serial Number:       DG6QGX2/3146033589114229
  │   GUID:                cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
  │   Device Flags:        • Updatable
  │                        • Requires AC power
  │                        • Supported on remote server
  │                        • Device update needs activation
  │                        • Device stages updates
  │                        • Device can recover flash failures
  │                        • Device is usable for the duration of the update
  │
  └─ Embedded Controller Update:
        New version:       01.00.00.04
        Remote ID:         lvfs-testing
        Summary:           Update for the Embedded controller within a Dell dock
        License:           Proprietary
        Size:              131.0 kB
        Vendor:            Dell Inc.
        Duration:          1 minute
        Flags:             is-upgrade
        Description:       Updated version to 01.00.00.04.
```
7. Install update again:
```shell
$ sudo fwupdmgr upgrade
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
Upgrade available for Package level of Dell dock from 01.00.14.00 to 01.00.14.01
Downloading 01.00.14.01 for Package level of Dell dock...
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Updating Package level of Dell dock…                             ]
Restarting device…       [***************************************]
Updating WD19TB…         [  -                                    ]
Writing…                 [***************************************]
Updating Package level of Dell dock…
Idle…                    [***************************************]
Updating WD19TB…
Idle…                    [***************************************]
Successfully installed firmware
Upload message: 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive; 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive
Successfully uploaded 1 report
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• WD19TB has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version
```
8. Check for updates again:
```shell
$ sudo fwupdmgr get-updates
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
• Package level of Dell dock has the latest available firmware version
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• WD19TB has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version
```
9. Power cycle the dock again
10. Check for available updates again:
```shell
$ sudo fwupdmgr get-updates
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version
Latitude 5491
│
├─Package level of Dell dock:
│ │   Device ID:           b5a854df85ab30fff48e4365ec7ad2249c90806e
│ │   Summary:             A representation of dock update status
│ │   Current version:     01.00.14.00
│ │   Vendor:              Dell Inc. (USB:0x413C)
│ │   Install Duration:    5 seconds
│ │   GUID:                8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
│ │   Device Flags:        • Updatable
│ │                        • Supported on remote server
│ │                        • Device can recover flash failures
│ │                        • Device is usable for the duration of the update
│ │
│ └─WD19/WD19DC/WDTB Device Update:
│       New version:       01.00.14.01
│       Remote ID:         lvfs-testing
│       Summary:           Update package for the WD19 family
│       License:           Proprietary
│       Size:              24 bytes
│       Details:           https://www.dell.com/support/article/sln320770/
│       Vendor:            Dell Inc.
│       Duration:          5 seconds
│       Flags:             is-upgrade
│       Description:       -Addressed rare video/display issues related to isolated combinations of host PCs, discrete GPUs and monitors.
│
│       -Improved the compatibility of the Dock firmware update utility.
│
│       -Updated firmware to comply with Apple certification requirements, which is applicable to the Dell Thunderbolt Dock - WD19TB only. Note that WD19TB is not fully compatible with Apple USB-C hosts.
│
└─WD19TB:
  │   Device ID:           570867f4ddda9915445da59bd85cd0e0e507270e
  │   Summary:             High performance dock
  │   Current version:     01.00.00.00
  │   Minimum Version:     01.00.00.00
  │   Vendor:              Dell Inc. (USB:0x413C)
  │   Install Duration:    1 minute
  │   Serial Number:       DG6QGX2/3146033589114229
  │   GUID:                cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
  │   Device Flags:        • Updatable
  │                        • Requires AC power
  │                        • Supported on remote server
  │                        • Device update needs activation
  │                        • Device stages updates
  │                        • Device can recover flash failures
  │                        • Device is usable for the duration of the update
  │
  └─ Embedded Controller Update:
        New version:       01.00.00.04
        Remote ID:         lvfs-testing
        Summary:           Update for the Embedded controller within a Dell dock
        License:           Proprietary
        Size:              131.0 kB
        Vendor:            Dell Inc.
        Duration:          1 minute
        Flags:             is-upgrade
        Description:       Updated version to 01.00.00.04.
```
11. Stop doing this because it is being reverted

**Expected behavior**
Update should be persisted and don't appear again after a power cycle.

**fwupd version information**
```shell
$ fwupdmgr --version
client version:	1.3.10
compile-time dependency versions
	gusb:	0.3.4
	efivar:	37
daemon version:	1.3.10
```

It is a version of fwupd currently available in Debian Testing.

**fwupd device information**
Please provide the output of the external fwupd devices recognized in your system.

```shell
$ sudo fwupdmgr get-devices --filter=~internal
Latitude 5491
│
└─WD19TB:
  │   Device ID:           570867f4ddda9915445da59bd85cd0e0e507270e
  │   Summary:             High performance dock
  │   Current version:     01.00.00.00
  │   Minimum Version:     01.00.00.00
  │   Vendor:              Dell Inc. (USB:0x413C)
  │   Install Duration:    1 minute
  │   Serial Number:       DG6QGX2/3146033589114229
  │   GUID:                cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
  │   Device Flags:        • Updatable
  │                        • Requires AC power
  │                        • Supported on remote server
  │                        • Device update needs activation
  │                        • Device stages updates
  │                        • Device can recover flash failures
  │                        • Device is usable for the duration of the update
  │ 
  ├─Thunderbolt controller in Dell dock:
  │     Device ID:         761cc3c3bbbdfdc750829548a245d5b3a240650a
  │     Summary:           Thunderbolt controller
  │     Current version:   43.00
  │     Vendor:            Dell Inc. (TBT:0x00D4)
  │     Install Duration:  22 seconds
  │     GUID:              c94770ca-1773-592c-b20a-e87243bc7cd0 ← TBT-00d4b070
  │     Device Flags:      • Updatable
  │                        • Requires AC power
  │                        • Supported on remote server
  │                        • Device stages updates
  │   
  ├─Package level of Dell dock:
  │     Device ID:         b5a854df85ab30fff48e4365ec7ad2249c90806e
  │     Summary:           A representation of dock update status
  │     Current version:   01.00.14.00
  │     Vendor:            Dell Inc. (USB:0x413C)
  │     Install Duration:  5 seconds
  │     GUID:              8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
  │     Device Flags:      • Updatable
  │                        • Supported on remote server
  │                        • Device can recover flash failures
  │                        • Device is usable for the duration of the update
  │   
  ├─RTS5413 in Dell dock:
  │     Device ID:         0acceea54e71c4d8002593822afe0f4705616613
  │     Summary:           USB 3.1 Generation 1 Hub
  │     Current version:   01.21
  │     Vendor:            Dell Inc. (USB:0x413C)
  │     Install Duration:  14 seconds
  │     GUIDs:             86fb40c0-8bf5-5a8b-a4ad-3156cf6bfaf4 ← USB\VID_413C&PID_B06F&REV_0101
  │                        b27d25f1-019d-5718-b41a-02ddaefe5577 ← USB\VID_413C&PID_B06F
  │                        ac5b774c-b49d-566b-9255-85f0f7f8a4ed ← USB\VID_413C&PID_B06F&hub
  │     Device Flags:      • Updatable
  │                        • Requires AC power
  │                        • Supported on remote server
  │                        • Device stages updates
  │                        • Device is usable for the duration of the update
  │   
  ├─RTS5487 in Dell dock:
  │     Device ID:         96969b82d977fdcbf607df084ef0dcf10119409b
  │     Summary:           USB 3.1 Generation 2 Hub
  │     Current version:   01.47
  │     Vendor:            Dell Inc. (USB:0x413C)
  │     Install Duration:  3 seconds
  │     GUIDs:             707c63d2-e597-5c40-84db-9b1bb4c48d96 ← USB\VID_413C&PID_B06E&REV_0101
  │                        acfcd89b-105d-55b9-b85b-08bf8508f38c ← USB\VID_413C&PID_B06E
  │                        568ffa1e-a0db-5287-9ea3-872b60f7730b ← USB\VID_413C&PID_B06E&hub
  │     Device Flags:      • Updatable
  │                        • Requires AC power
  │                        • Supported on remote server
  │                        • Device stages updates
  │                        • Device is usable for the duration of the update
  │   
  └─VMM5331 in Dell dock:
        Device ID:         228ac6846b64d532dd1ea1b7e651e8f5f55fbc34
        Summary:           Multi Stream Transport controller
        Current version:   05.04.03
        Vendor:            Dell Inc. (USB:0x413C)
        Install Duration:  6 minutes
        GUID:              89fec0b6-6b76-5008-b82c-5e5c6c164007 ← MST-panamera-vmm5331-259
        Device Flags:      • Updatable
                           • Requires AC power
                           • Supported on remote server
                           • Device stages updates
                           • Device is usable for the duration of the update
```

**Dock SKU**
Please mention which module is installed in your WD19.

- [ ] WD19 (Single-C)
- [*] WD19TB (Thunderbolt)
- [ ] WD19DC (Dual-C)

**Peripherals connected to the dock**
Please describe all devices connected to the dock.  Be as specific as possible,
including USB devices, hubs, monitors, and downstream type-C devices.
1. AOC monitor via HDMI cable
2. AOC monitor via DP cable
3. Logitech USB keyboard
4. Logitech USB mouse
5. Microsoft USB webcam
6. Speakers via 3.5 jack

**Verbose daemon logs**
First enable daemon verbose logs collection.
```shell
fwupdmgr modify-config "VerboseDomains" "*"

$ sudo fwupdmgr modify-config "VerboseDomains" "*"
Restart the daemon to make the change effective? [Y|n]: y
Successfully modified configuration value

$ sudo fwupdmgr update
• Thunderbolt Controller has no available firmware updates
• Thunderbolt controller in Dell dock has the latest available firmware version
Upgrade available for Package level of Dell dock from 01.00.14.00 to 01.00.14.01
Downloading 01.00.14.01 for Package level of Dell dock...
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Updating Package level of Dell dock…                             ]
Restarting device…       [***************************************]
Updating WD19TB…         [  -                                    ]
Writing…                 [***************************************]
Updating Package level of Dell dock…
Idle…                    [***************************************]
Updating WD19TB…
Idle…                    [***************************************]
Successfully installed firmware
Upload message: 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive; 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive
Successfully uploaded 1 report
• RTS5413 in Dell dock has the latest available firmware version
• RTS5487 in Dell dock has the latest available firmware version
• VMM5331 in Dell dock has the latest available firmware version
• WD19TB has the latest available firmware version
• SSDPEKKF512G8 NVMe INTEL 512GB has no available firmware updates
• System Firmware has the latest available firmware version

```

Then try to reproduce the issue.  Even if it doesn't reproduce, please attach the
daemon verbose logs collected from the system journal.
```shell
$ journalctl -b -u fwupd.service
```
Log is too long for an issue so I've posted it here: https://gist.github.com/sitnik/34298496fecadb3cb71c19b1ffc589d5

**Additional questions**
- Operating system and version: -- Debian Testing, updated today
- Have you tried unplugging the dock or any peripherals from your machine? -- No
- Have you tried to power cycle the dock from the AC adapter? -- Yes
- Is this a regression? -- Don't know

**Comment by superm1** [comment] 2020-06-16 12:28
When you say you power cycled the dock - did you unplug it from the system or from the wall ac adapter? It needs to be kept plugged into wall ac adapter to complete the update, but unplugged from system.

**Comment by sitnik** [comment] 2020-06-16 13:36
I unplugged it from the ac adapter, but it was connected to laptop whole time.

**Comment by sitnik** [comment] 2020-06-16 13:36
I'll try that.

**Comment by sitnik** [comment] 2020-06-16 13:45
Ok, after unplugging/plugging back laptop to the dock updates don't show up anymore in `fwupdmgr get-updates` output. I even tried to unplug the dock from both laptop and ac adapter and plug it again.

It looks like it's finally updated. All components are showing right versions for the FW update in testing. Thanks.

**Comment by superm1** [comment] 2020-06-16 13:48
Well glad it got updated for you.

I'm curious; what led you to think you should unplug the AC adapter though on the dock?  Was it bad wording somewhere?

**Comment by superm1** [comment] 2020-06-17 16:37
Oh, I think I see why you could have drawn that conclusion...

```
			fu_device_set_update_error (device, "An update is pending "
							    "next time the dock is "
							    "unplugged");
```
https://github.com/fwupd/fwupd/blob/master/plugins/dell-dock/fu-dell-dock-i2c-ec.c#L526

There is nothing specifying unplugged from **host** or **AC adapter**.  It definitely needs to be unplugged from host.  I'll send up a PR to clarify this.

**Comment by sitnik** [comment] 2020-06-17 20:10
I've seen message `Upload message: 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive; 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive` in `fwupdmgr upgrade` output and this worried me. So I've tried the usual 'have you tried turning it off and on again?' thing by unplugging ac adapter from switch.

Nothing in `fwupdmgr upgrade` output states that I need to unplug Thunderbolt cable from the laptop to finish the upgrade. So I decided this is bug and wrote this report.

Thank you and Richard for fwupd. Being able to upgrade firmware on the laptop and dock from Linux still a very good experience comparing to what we had a few years ago.

**Comment by sitnik** [comment] 2020-06-17 20:12
> Oh, I think I see why you could have drawn that conclusion...
> 
> ```
> 			fu_device_set_update_error (device, "An update is pending "
> 							    "next time the dock is "
> 							    "unplugged");
> ```
> 
> https://github.com/fwupd/fwupd/blob/master/plugins/dell-dock/fu-dell-dock-i2c-ec.c#L526
> 
> There is nothing specifying unplugged from **host** or **AC adapter**. It definitely needs to be unplugged from host. I'll send up a PR to clarify this.

This doesn't exists in version 1.3.10. Is 1.4 branch is considered stable?

I think we can close the issue now.

**Comment by superm1** [comment] 2020-06-17 20:19
>I've seen message Upload message: 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive; 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive in fwupdmgr upgrade output and this worried me. So I've tried the usual 'have you tried turning it off and on again?' thing by unplugging ac adapter from switch.

Ah thanks for sharing this.  It was specifically related to uploading the report that failed.  @hughsie this seems unexpected to me, anything jump out at you?

>Nothing in fwupdmgr upgrade output states that I need to unplug Thunderbolt cable from the laptop to finish the upgrade. So I decided this is bug and wrote this report.

Huh, that's actually not expected either.  You were supposed to see an `UpdateMessage` through this code flow.  That should have told you about the update finishing on unplug.

https://github.com/fwupd/fwupd/blob/master/src/fu-util.c#L1831
https://github.com/fwupd/fwupd/blob/master/src/fu-util.c#L585
https://github.com/fwupd/fwupd/blob/master/src/fu-util.c#L147

>This doesn't exist in version 1.3.10. Is 1.4 branch considered stable?

It should:
https://github.com/fwupd/fwupd/blob/1_3_X/plugins/dell-dock/fu-dell-dock-i2c-ec.c#L537
And yes 1.4.x is stable.

**Comment by superm1** [comment] 2020-06-17 20:19
>Thank you and Richard for fwupd. Being able to upgrade firmware on the laptop and dock from Linux still a very good experience comparing to what we had a few years ago.

Thanks!

**Comment by superm1** [comment] 2020-06-17 21:07
>Huh, that's actually not expected either. You were supposed to see an UpdateMessage through this code flow. That should have told you about the update finishing on unplug.

I think LVFS might have lost the `LVFS::UpdateMessage` key when the XML got rewritten... I checked a 1.0.14 CAB file from LVFS and compared it to one that wasn't yet uploaded to LVFS and notice the key is missing.  This looks like an LVFS bug to me, opened an issue here: https://github.com/fwupd/lvfs-website/issues/662

**Comment by superm1** [comment] 2020-06-17 21:37
> 843b87bf2ce45589a8b00b0799a650a92072bafb did not match any known firmware archive;

So this is coming from LVFS back to the client.  From here:
https://github.com/fwupd/lvfs-website/blob/c358f0d42690c1edcda54f05af9940826d631231/lvfs/reports/routes.py#L200

My suspicion is that it's actually caused by the mucking with metadata to make it "WD19TB" (which we did as a result of https://github.com/fwupd/firmware-dell/issues/28#issuecomment-644178727).  This caused the CAB to be rebuilt, and then the checksum on LVFS to change too.  So you have old file downloaded, try to upload a report for it and LVFS says uhhh what's that, I don't recognize it because it didn't keep a copy of the old checksum around.

**Comment by hughsie** [comment] 2020-06-18 10:45
>  This caused the CAB to be rebuilt, and then the checksum on LVFS to change too

**Comment by superm1** [comment] 2020-06-18 12:37
I think the re-signing thing is pretty rare while in testing/stable, no?

**Comment by hughsie** [comment] 2020-06-18 12:41
> I think the re-signing thing is pretty rare while in testing/stable, no?

Yes, it's something only the admin team can do. I've only done it 3 times every I think. What is more common is:

 * Upload to embargo (->sign)
 * Push to stable
 * eeek, forgot something
 * Push to embargo
 * Fix the update description or add CVEs (->sign)
 * Push to stable

**Comment by superm1** [comment] 2020-06-18 13:21
> an obsolete fwupd version is that really something we want to hold against the newly modified firmware?

Considering that the going back to embargo could mean you add CHIDs or change protocols, I suppose that actually could have a big impact on reports being run on invalid SKUs.

I would rather see the failures for that but not hold it against automatic downgrades.  So maybe a 4th class to `success`/`definite fail`/`known issues`/`possible fail`  Or feed it back into known issues?

**Comment by bulletmark** [comment] 2020-06-23 03:07
Apart from disconnecting the dock from the laptop, is there anything else one needs to do? I have waited 15 mins, tried a power cycle of the dock, but it always shows the following "updates will complete" message:
```
─WD19TB:
│ │   Device ID:           570867f4ddda9915445da59bd85cd0e0e507270e
│ │   Summary:             High performance dock
│ │   Current version:     01.00.00.04
│ │   Minimum Version:     01.00.00.00
│ │   Vendor:              Dell Inc. (USB:0x413C)
│ │   Install Duration:    1 minute
│ │   Serial Number:       4DN5523/3159128927644594
│ │   Update Message:      Updates will complete after the dock is unplugged. The dock will be unavailable for approximately 1 minute.
│ │   GUID:                cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
│ │   Device Flags:        • Updatable
│ │                        • Requires AC power
│ │                        • Supported on remote server
│ │                        • Device stages updates
│ │                        • Device can recover flash failures
│ │                        • Device is usable for the duration of the update
```
Did the update again and seem to download ok but same problem no matter how long I wait.

**Comment by superm1** [comment] 2020-06-23 03:09
@bulletmark The dock needs to be unplugged from the machine, not the AC adapter..
If that is what you were doing and it's having problems, please file a separate issue so we can get all your logs and relevant details.

**Comment by bulletmark** [comment] 2020-06-23 03:10
As first per sentence I am unplugging from the laptop. I will raise another issue.

**Comment by superm1** [comment] 2020-06-23 21:59
The several issues in here got resolved, I'm going to close this one.  If you find this issue, and also have a WD19TB upgrade problem, please file a new issue using the template so that we can get all your relevant logs.

**Closed by superm1** 2020-06-23 21:59 UTC
Labels: bug
