### ISSUE TITLE
Unsupported daemon version 1.3.5, client version is 1.2.10

### ISSUE THREAD

**Issue by amilopowers** [fwupd/fwupd#1668] opened 2019-12-21 14:00 UTC
```shell
$ fwupdmgr --version
**client version:	1.2.10
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
daemon version:	1.3.5
**
```
```shell
$ fwupdmgr get-devices
**Unsupported daemon version 1.3.5, client version is 1.2.10
**
```

```shell
$ efibootmgr -v
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000
Boot0000* ubuntu	HD(1,GPT,05a6f050-f9b4-4569-8a65-2fd5b62aa971,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)
Boot0001* Manjaro	HD(1,GPT,d40bd23f-591c-405f-af55-e0125cc397c6,0x1000,0x96000)/File(\EFI\Manjaro\grubx64.efi)
Boot0003* Linux Boot Manager	HD(1,GPT,02978b8e-2681-4ffd-9cc6-044fa4e44449,0x40,0xf4240)/File(\EFI\systemd\systemd-bootx64.efi)

```

```shell
$ efivar -l | grep fw
**INSERT OUTPUT HERE**
**This is only required if you use the UEFI plugin**
```

```shell
$ tree /boot
**INSERT OUTPUT HERE**
**This is only required if you use the UEFI plugin**
**We're looking for any `.cap` files and the location of `fwupx64.efi`**
```

Please answer the following questions:

- Operating system and version: Ubuntu 19.10
- How did you install fwupd: apt-get
- Have you tried rebooting? yes
- Are you using an NVMe disk? yes
- Is secure boot enabled (only for the UEFI plugin)? no

**Comment by hughsie** [comment] 2019-12-22 08:40
Duplicate of https://github.com/fwupd/fwupd/issues/1633 I'm afraid.

**Closed by hughsie** 2019-12-22 08:40 UTC
