### ISSUE TITLE
FuUsbDevice failed to load BOS descriptor from USB device: USB error on device 552d:4348 : No such device (it may have been disconnected) [-4]

### ISSUE THREAD

**Issue by soyersoyer** [fwupd/fwupd#6882] opened 2024-03-06 16:09 UTC
**Describe the bug**
When I connect my USB Midi cable, it always disconnects when fwupd is running.

It works when fwupd is not running.

márc 06 16:55:04 fedori kernel: usb 9-1: new full-speed USB device number 67 using xhci_hcd
márc 06 16:55:04 fedori kernel: usb 9-1: New USB device found, idVendor=552d, idProduct=4348, bcdDevice=f1.10
márc 06 16:55:04 fedori kernel: usb 9-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
márc 06 16:55:04 fedori kernel: usb 9-1: Product: USB Midi        
márc 06 16:55:04 fedori kernel: usb 9-1: Quirk or no altset; falling back to MIDI 1.0
márc 06 16:55:04 fedori kernel: usb 9-1: USB disconnect, device number 67
márc 06 16:55:04 fedori fwupd[53648]: 15:55:04.803 FuUsbDevice          failed to load BOS descriptor from USB device: USB error on device 552d:4348 : No such device (it may have been disconnected) [-4]

**Steps to Reproduce**
Connect the USB Midi cable, watch the journal

**Expected behavior**
It should work as without fwupd.

**fwupd version information**
Name         : fwupd
Version      : 1.9.14
Release      : 1.fc39

```shell
fwupdmgr --version
```
```
compile   com.hughsie.libxmlb           0.3.15
compile   com.hughsie.libjcat           0.2.1
compile   org.freedesktop.fwupd         1.9.14
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.8
runtime   com.hughsie.libjcat           0.2.1
runtime   org.freedesktop.gusb          0.4.8
runtime   org.freedesktop.fwupd         1.9.14
runtime   org.kernel                    6.8.0-rc7
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
dnf

**Additional questions**

- Operating system and version: Fedora F39
- Have you tried rebooting? N
- Is this a regression? I don't know.

**Comment by superm1** [comment] 2024-03-06 16:53
Should be a duplicate of https://github.com/fwupd/fwupd/issues/6871, fixed by https://github.com/fwupd/fwupd/commit/f92ea06110f5075d7b94c90ad1a637f6b43a647c

**Closed** 2024-03-06 17:35 UTC
Labels: bug
