### ISSUE TITLE
Undetected EC/BIOS with EFI+GRUB (Thinkpad X1C 7th)

### ISSUE THREAD

**Issue by in0ni** [fwupd/fwupd#1453] opened 2019-10-10 18:31 UTC
I have tried to update my EC/BIOS using the following instructions to copy fwupdx64.efi to my ESP: https://wiki.archlinux.org/index.php/Fwupd#Setup_for_UEFI_BIOS_upgrade but constantly get "No supported devices found".

I have copied my fwupdx64.efi to both /efi/EFI and /efi/EFI/GRUB, without any luck. I never get *.cap files generated, or perhaps I need to manually do this?

From what I can tell I can never get a LVFS to show up in efibootmgr... I suspect I am missing something simple here. Any help would be greatly appreciated, 

```shell
$ fwupdmgr --version
client version:	1.3.2
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
daemon version:	1.3.2
```

```shell
$ fwupdmgr get-devices
20QDCTO1WW
│
├─ThinkPad X1 Yoga 4th / Carbon 7th Thunderbolt Controller:
│     Device ID:           ee4cb94af47a4c1dba831e5080a63bf5d53fa1c7
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     43.00
│     Vendor:              Lenovo (TBT:0x0109)
│     Flags:               internal|updatable|require-ac|supported|registered
│     GUID:                c7920601-0cda-507f-851e-92229eb1d370
│   
├─Unifying Receiver:
│     Device ID:           82091cc2e67e8e248d8dad9ac847708118484457
│     Summary:             A miniaturised USB wireless receiver
│     Current version:     RQR12.10_B0032
│     Bootloader Version:  BOT01.02_B0015
│     Vendor:              Logitech (USB:0x046D)
│     Install Duration:    30 seconds
│     Flags:               updatable|supported|registered
│     GUIDs:               9d131a0c-a606-580f-8eda-80587250b8d6
│                          279ed287-3607-549e-bacc-f873bb9838c4
│   
└─WDC PC SN720 SDAQNTW-512G-1001:
      Device ID:           3743975ad7f64f8d6575a9ae49fb3a8856fe186f
      Summary:             NVM Express Solid State Drive
      Current version:     10160101
      Vendor:              Sandisk Corp (NVME:0x15B7)
      Flags:               internal|updatable|require-ac|registered|needs-reboot
      GUIDs:               ff2112dc-038c-596d-90ca-d43c5077c6ec
                           63af1441-fb24-5368-b450-886fbc98610b
```

```shell
$ fwupdmgr get-devices --show-all-devices
20QDCTO1WW
│
├─ThinkPad X1 Yoga 4th / Carbon 7th Thunderbolt Controller:
│     Device ID:           ee4cb94af47a4c1dba831e5080a63bf5d53fa1c7
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     43.00
│     Vendor:              Lenovo (TBT:0x0109)
│     Flags:               internal|updatable|require-ac|supported|registered
│     GUID:                c7920601-0cda-507f-851e-92229eb1d370
│   
├─UHD Graphics 620 (Whiskey Lake):
│     Device ID:           bbbf1ce3d1cf15550c3760b354592040292415bb
│     Current version:     02
│     Vendor:              Intel Corporation (PCI:0x8086)
│     Flags:               internal|registered
│     GUIDs:               6986c21a-0f3f-5538-bcef-fe4e8cda7ab7
│                          52aa8ac7-c837-561f-af32-b7979cd2f6ed
│   
├─Unifying Receiver:
│     Device ID:           82091cc2e67e8e248d8dad9ac847708118484457
│     Summary:             A miniaturised USB wireless receiver
│     Current version:     RQR12.10_B0032
│     Bootloader Version:  BOT01.02_B0015
│     Vendor:              Logitech (USB:0x046D)
│     Install Duration:    30 seconds
│     Flags:               updatable|supported|registered
│     GUIDs:               9d131a0c-a606-580f-8eda-80587250b8d6
│                          279ed287-3607-549e-bacc-f873bb9838c4
│   
└─WDC PC SN720 SDAQNTW-512G-1001:
      Device ID:           3743975ad7f64f8d6575a9ae49fb3a8856fe186f
      Summary:             NVM Express Solid State Drive
      Current version:     10160101
      Vendor:              Sandisk Corp (NVME:0x15B7)
      Flags:               internal|updatable|require-ac|registered|needs-reboot
      GUIDs:               ff2112dc-038c-596d-90ca-d43c5077c6ec
                           63af1441-fb24-5368-b450-886fbc98610b
```

```shell
$ efibootmgr -v
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0010,0011,0012,0013,0014,0015,0019,001A,001B,001C,001D,001E,001F,0020,0021,0022,0023,0024
Boot0000* GRUB	HD(1,GPT,276afe19-2bc3-864d-bab9-670f88e0fc15,0x800,0x82000)/File(\EFI\GRUB\grubx64.efi)
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  Regulatory Information	FvFile(478c92a0-2622-42b7-a65d-5894169e4d24)
Boot0015  ThinkShield secure wipe	FvFile(3593a0d5-bd52-43a0-808e-cbff5ece2477)
Boot0016  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0017  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0018  MEBx Hot Key	FvFile(ac6fd56a-3d41-4efd-a1b9-870293811a28)
Boot0019* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot001A* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot001B* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001C* NVMe1	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a401)
Boot001D* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001E* ATA HDD1	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f601)
Boot001F* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot0020* PXE BOOT	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot0021* HTTPS BOOT	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,ad38ccbbf7edf04d959cf42aa74d3650)/Uri()
Boot0022* LENOVO CLOUD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,ad38ccbbf7edf04d959cf42aa74d3650)/Uri(https://download.lenovo.com/pccbbs/cdeploy/efi/boot.efi)
Boot0023  Other CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a35406)
Boot0024  Other HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f606)
Boot0025* IDER BOOT CDROM	PciRoot(0x0)/Pci(0x16,0x2)/Ata(0,1,0)
Boot0026* IDER BOOT Floppy	PciRoot(0x0)/Pci(0x16,0x2)/Ata(0,0,0)
Boot0027* ATA HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f6)
Boot0028* ATAPI CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a354)
```

```shell
$ efivar -l | grep fw
**no output**
```

```shell
$ tree /boot
/boot/
├── grub
│   ├── fonts
│   │   └── unicode.pf2
│   ├── grub.cfg
│   ├── grubenv
│   ├── themes
│   │   └── starfield
│   │       ├── blob_w.png
│   │       ├── boot_menu_c.png
│   │       ├── boot_menu_e.png
│   │       ├── boot_menu_ne.png
│   │       ├── boot_menu_n.png
│   │       ├── boot_menu_nw.png
│   │       ├── boot_menu_se.png
│   │       ├── boot_menu_s.png
│   │       ├── boot_menu_sw.png
│   │       ├── boot_menu_w.png
│   │       ├── COPYING.CC-BY-SA-3.0
│   │       ├── dejavu_10.pf2
│   │       ├── dejavu_12.pf2
│   │       ├── dejavu_14.pf2
│   │       ├── dejavu_16.pf2
│   │       ├── dejavu_bold_14.pf2
│   │       ├── README
│   │       ├── slider_c.png
│   │       ├── slider_n.png
│   │       ├── slider_s.png
│   │       ├── starfield.png
│   │       ├── terminal_box_c.png
│   │       ├── terminal_box_e.png
│   │       ├── terminal_box_ne.png
│   │       ├── terminal_box_n.png
│   │       ├── terminal_box_nw.png
│   │       ├── terminal_box_se.png
│   │       ├── terminal_box_s.png
│   │       ├── terminal_box_sw.png
│   │       ├── terminal_box_w.png
│   │       └── theme.txt
│   └── x86_64-efi
│       ├── acpi.mod
│       ├── adler32.mod
│       ├── affs.mod
│       ├── afs.mod
│       ├── ahci.mod
│       ├── all_video.mod
│       ├── aout.mod
│       ├── appleldr.mod
│       ├── archelp.mod
│       ├── ata.mod
│       ├── at_keyboard.mod
│       ├── backtrace.mod
│       ├── bfs.mod
│       ├── bitmap.mod
│       ├── bitmap_scale.mod
│       ├── blocklist.mod
│       ├── boot.mod
│       ├── boottime.mod
│       ├── bsd.mod
│       ├── bswap_test.mod
│       ├── btrfs.mod
│       ├── bufio.mod
│       ├── cacheinfo.mod
│       ├── cat.mod
│       ├── cbfs.mod
│       ├── cbls.mod
│       ├── cbmemc.mod
│       ├── cbtable.mod
│       ├── cbtime.mod
│       ├── chain.mod
│       ├── cmdline_cat_test.mod
│       ├── cmp.mod
│       ├── cmp_test.mod
│       ├── command.lst
│       ├── configfile.mod
│       ├── core.efi
│       ├── cpio_be.mod
│       ├── cpio.mod
│       ├── cpuid.mod
│       ├── crc64.mod
│       ├── cryptodisk.mod
│       ├── crypto.lst
│       ├── crypto.mod
│       ├── cs5536.mod
│       ├── ctz_test.mod
│       ├── datehook.mod
│       ├── date.mod
│       ├── datetime.mod
│       ├── diskfilter.mod
│       ├── disk.mod
│       ├── div.mod
│       ├── div_test.mod
│       ├── dm_nv.mod
│       ├── echo.mod
│       ├── efifwsetup.mod
│       ├── efi_gop.mod
│       ├── efinet.mod
│       ├── efi_uga.mod
│       ├── ehci.mod
│       ├── elf.mod
│       ├── eval.mod
│       ├── exfat.mod
│       ├── exfctest.mod
│       ├── ext2.mod
│       ├── extcmd.mod
│       ├── f2fs.mod
│       ├── fat.mod
│       ├── file.mod
│       ├── fixvideo.mod
│       ├── font.mod
│       ├── fshelp.mod
│       ├── fs.lst
│       ├── functional_test.mod
│       ├── gcry_arcfour.mod
│       ├── gcry_blowfish.mod
│       ├── gcry_camellia.mod
│       ├── gcry_cast5.mod
│       ├── gcry_crc.mod
│       ├── gcry_des.mod
│       ├── gcry_dsa.mod
│       ├── gcry_idea.mod
│       ├── gcry_md4.mod
│       ├── gcry_md5.mod
│       ├── gcry_rfc2268.mod
│       ├── gcry_rijndael.mod
│       ├── gcry_rmd160.mod
│       ├── gcry_rsa.mod
│       ├── gcry_seed.mod
│       ├── gcry_serpent.mod
│       ├── gcry_sha1.mod
│       ├── gcry_sha256.mod
│       ├── gcry_sha512.mod
│       ├── gcry_tiger.mod
│       ├── gcry_twofish.mod
│       ├── gcry_whirlpool.mod
│       ├── geli.mod
│       ├── gettext.mod
│       ├── gfxmenu.mod
│       ├── gfxterm_background.mod
│       ├── gfxterm_menu.mod
│       ├── gfxterm.mod
│       ├── gptsync.mod
│       ├── grub.efi
│       ├── gzio.mod
│       ├── halt.mod
│       ├── hashsum.mod
│       ├── hdparm.mod
│       ├── hello.mod
│       ├── help.mod
│       ├── hexdump.mod
│       ├── hfs.mod
│       ├── hfspluscomp.mod
│       ├── hfsplus.mod
│       ├── http.mod
│       ├── iorw.mod
│       ├── iso9660.mod
│       ├── jfs.mod
│       ├── jpeg.mod
│       ├── keylayouts.mod
│       ├── keystatus.mod
│       ├── ldm.mod
│       ├── legacycfg.mod
│       ├── legacy_password_test.mod
│       ├── linux16.mod
│       ├── linux.mod
│       ├── loadbios.mod
│       ├── loadenv.mod
│       ├── loopback.mod
│       ├── lsacpi.mod
│       ├── lsefimmap.mod
│       ├── lsefi.mod
│       ├── lsefisystab.mod
│       ├── lsmmap.mod
│       ├── ls.mod
│       ├── lspci.mod
│       ├── lssal.mod
│       ├── luks.mod
│       ├── lvm.mod
│       ├── lzopio.mod
│       ├── macbless.mod
│       ├── macho.mod
│       ├── mdraid09_be.mod
│       ├── mdraid09.mod
│       ├── mdraid1x.mod
│       ├── memdisk.mod
│       ├── memrw.mod
│       ├── minicmd.mod
│       ├── minix2_be.mod
│       ├── minix2.mod
│       ├── minix3_be.mod
│       ├── minix3.mod
│       ├── minix_be.mod
│       ├── minix.mod
│       ├── mmap.mod
│       ├── moddep.lst
│       ├── modinfo.sh
│       ├── morse.mod
│       ├── mpi.mod
│       ├── msdospart.mod
│       ├── mul_test.mod
│       ├── multiboot2.mod
│       ├── multiboot.mod
│       ├── nativedisk.mod
│       ├── net.mod
│       ├── newc.mod
│       ├── nilfs2.mod
│       ├── normal.mod
│       ├── ntfscomp.mod
│       ├── ntfs.mod
│       ├── odc.mod
│       ├── offsetio.mod
│       ├── ohci.mod
│       ├── part_acorn.mod
│       ├── part_amiga.mod
│       ├── part_apple.mod
│       ├── part_bsd.mod
│       ├── part_dfly.mod
│       ├── part_dvh.mod
│       ├── part_gpt.mod
│       ├── partmap.lst
│       ├── part_msdos.mod
│       ├── part_plan.mod
│       ├── part_sun.mod
│       ├── part_sunpc.mod
│       ├── parttool.lst
│       ├── parttool.mod
│       ├── password.mod
│       ├── password_pbkdf2.mod
│       ├── pata.mod
│       ├── pbkdf2.mod
│       ├── pbkdf2_test.mod
│       ├── pcidump.mod
│       ├── pgp.mod
│       ├── play.mod
│       ├── png.mod
│       ├── priority_queue.mod
│       ├── probe.mod
│       ├── procfs.mod
│       ├── progress.mod
│       ├── raid5rec.mod
│       ├── raid6rec.mod
│       ├── random.mod
│       ├── rdmsr.mod
│       ├── read.mod
│       ├── reboot.mod
│       ├── regexp.mod
│       ├── reiserfs.mod
│       ├── relocator.mod
│       ├── romfs.mod
│       ├── scsi.mod
│       ├── search_fs_file.mod
│       ├── search_fs_uuid.mod
│       ├── search_label.mod
│       ├── search.mod
│       ├── serial.mod
│       ├── setjmp.mod
│       ├── setjmp_test.mod
│       ├── setpci.mod
│       ├── sfs.mod
│       ├── shift_test.mod
│       ├── shim_lock.mod
│       ├── signature_test.mod
│       ├── sleep.mod
│       ├── sleep_test.mod
│       ├── spkmodem.mod
│       ├── squash4.mod
│       ├── strtoull_test.mod
│       ├── syslinuxcfg.mod
│       ├── tar.mod
│       ├── terminal.lst
│       ├── terminal.mod
│       ├── terminfo.mod
│       ├── test_blockarg.mod
│       ├── testload.mod
│       ├── test.mod
│       ├── testspeed.mod
│       ├── tftp.mod
│       ├── tga.mod
│       ├── time.mod
│       ├── tpm.mod
│       ├── trig.mod
│       ├── tr.mod
│       ├── true.mod
│       ├── udf.mod
│       ├── ufs1_be.mod
│       ├── ufs1.mod
│       ├── ufs2.mod
│       ├── uhci.mod
│       ├── usb_keyboard.mod
│       ├── usb.mod
│       ├── usbms.mod
│       ├── usbserial_common.mod
│       ├── usbserial_ftdi.mod
│       ├── usbserial_pl2303.mod
│       ├── usbserial_usbdebug.mod
│       ├── usbtest.mod
│       ├── verifiers.mod
│       ├── video_bochs.mod
│       ├── video_cirrus.mod
│       ├── video_colors.mod
│       ├── video_fb.mod
│       ├── videoinfo.mod
│       ├── video.lst
│       ├── video.mod
│       ├── videotest_checksum.mod
│       ├── videotest.mod
│       ├── wrmsr.mod
│       ├── xfs.mod
│       ├── xnu.mod
│       ├── xnu_uuid.mod
│       ├── xnu_uuid_test.mod
│       ├── xzio.mod
│       ├── zfscrypt.mod
│       ├── zfsinfo.mod
│       ├── zfs.mod
│       └── zstd.mod
├── initramfs-linux-fallback.img
├── initramfs-linux.img
├── intel-ucode.img
└── vmlinuz-linux
```

```shell
$ tree /efi
/efi
└── EFI
    ├── fwupdx64.efi
    └── GRUB
        └── grubx64.efi
```

Please answer the following questions:

- Operating system and version: **Archlinux: 5.3.5-arch1-1-ARCH #1 SMP PREEMPT Mon Oct 7 19:03:08 UTC 2019 x86_64 GNU/Linux**
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): **pacman**
- Have you tried rebooting? **Yes, multiple times**
- Are you using an NVMe disk? **yes**
- Is secure boot enabled (only for the UEFI plugin)? **no**

I have also enabled "Flash BIOS Updating by End-User".

Thanks in advance.

**Comment by Viginox** [comment] 2019-10-12 16:35
I had the same issue on my **Lenovo Yoga X1 2019 (Gen 3).**

### What I've tried
I tried to uninstall **fwupd** and install it again. Nothing changed. Still not showing up all devices.
I tried to get information about an old update found in `~/.cache/fwupd`.
`fwupdmgr get-details ~/.cache/fwupd/<filename>.cap` resulted in following output
```
Decompressing…           [***************************************]
20LES09700
│
```
I downloaded the update from LVFS directly and tried to install it with `fwupdmgr install <filename>.cap` and just got the information that no supported device could be found.

### My Solution
The solution for me was to install snap and install fwupd from there. Then I had version 1.3.3 and everything worked like it did before.

[fwupd on Snap](https://snapcraft.io/fwupd)

output from `fwupdmgr --version`
```
client version:	1.3.3
checkout info:	1.3.2-5-g506ef63a
compile-time dependency versions
	gusb:	0.2.11
	efivar:	34
daemon version:	1.3.3
```
### My System
Running **Manjaro Linux 18.1.0 Juhraya** with Kernel **4.14.148-1-MANJARO**

**Comment by superm1** [comment] 2019-10-13 19:25
This sounds like a duplicate of https://github.com/fwupd/fwupd/issues/1460.
Install tpm2-tss and restart the daemon.

**Closed by superm1** 2019-10-13 19:25 UTC

**Comment by in0ni** [comment] 2019-10-14 03:33
@superm1 Thanks for the reference. Installing tpm2-tss only *partially* solved my issue. It seems that the system firmware is now showing up -- but I am still unable to update my [EC](https://fwupd.org/lvfs/device/com.lenovo.ThinkPadN2HHT.firmware), still get "No supported devices found". This update is required before updating BIOS.

Here are both the output of `get-devices` and the verbose output of the daemon logs -- please let me know if you need anything else from me -- and thanks in advance!

```shell
fwupdmgr get-devices --show-all-devices
20QDCTO1WW
│
├─ThinkPad X1 Yoga 4th / Carbon 7th Thunderbolt Controller:
│     Device ID:           ee4cb94af47a4c1dba831e5080a63bf5d53fa1c7
│     Summary:             Unmatched performance for high-speed I/O
│     Current version:     43.00
│     Vendor:              Lenovo (TBT:0x0109)
│     Flags:               internal|updatable|require-ac|supported|registered
│     GUID:                c7920601-0cda-507f-851e-92229eb1d370
│   
├─System Firmware:
│     Device ID:           123fd4143619569d8ddb6ea47d1d3911eb5ef07a
│     Current version:     N2HET30W (1.13 )
│     Vendor:              LENOVO
│     Update Error:        UEFI Capsule updates not available or enabled
│     Flags:               internal|require-ac|registered|needs-reboot
│     GUID:                230c8b18-8d9b-53ec-838b-6cfc0383493a
│   
├─UHD Graphics 620 (Whiskey Lake):
│     Device ID:           bbbf1ce3d1cf15550c3760b354592040292415bb
│     Current version:     02
│     Vendor:              Intel Corporation (PCI:0x8086)
│     Flags:               internal|registered
│     GUIDs:               6986c21a-0f3f-5538-bcef-fe4e8cda7ab7
│                          52aa8ac7-c837-561f-af32-b7979cd2f6ed
│   
├─Unifying Receiver:
│     Device ID:           82091cc2e67e8e248d8dad9ac847708118484457
│     Summary:             A miniaturised USB wireless receiver
│     Current version:     RQR12.10_B0032
│     Bootloader Version:  BOT01.02_B0015
│     Vendor:              Logitech (USB:0x046D)
│     Install Duration:    30 seconds
│     Flags:               updatable|supported|registered
│     GUIDs:               9d131a0c-a606-580f-8eda-80587250b8d6
│                          279ed287-3607-549e-bacc-f873bb9838c4
│   
└─WDC PC SN720 SDAQNTW-512G-1001:
      Device ID:           3743975ad7f64f8d6575a9ae49fb3a8856fe186f
      Summary:             NVM Express Solid State Drive
      Current version:     10160101
      Vendor:              Sandisk Corp (NVME:0x15B7)
      Flags:               internal|updatable|require-ac|registered|needs-reboot
      GUIDs:               ff2112dc-038c-596d-90ca-d43c5077c6ec
                           63af1441-fb24-5368-b450-886fbc98610b
```
Daemon logs:

```shell
-- Logs begin at Tue 2019-08-20 22:39:14 CST, end at Sun 2019-10-13 21:21:07 CST. --
Oct 13 21:04:56 xXx systemd[1]: Starting Firmware update daemon...
Oct 13 21:04:58 xXx fwupd[1791]: 03:04:58:0467 FuPluginUefi         Error opening directory “/sys/firmware/efi/esrt/entries”: No such file or directory
Oct 13 21:04:59 xXx systemd[1]: Started Firmware update daemon.
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0329 Fwupd                looking for os-release at /etc/os-release
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 FuConfig             loading /usr/share/fwupd/metainfo
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 XbSilo               file: cc14f2da-a69e-5ffd-af90-04c6986cf8ed, current:cc14f2da-a69e-5ffd-af90-04c6986cf8ed, cached: (null)
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 XbSilo               loading silo with file contents
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 FuConfig             using config path of /etc/fwupd
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 FuConfig             loading config from /etc/fwupd/remotes.d/vendor-directory.conf
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 FuConfig             loading config from /etc/fwupd/remotes.d/fwupd-tests.conf
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0330 FuConfig             loading config from /etc/fwupd/remotes.d/lvfs-testing.conf
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0331 FuConfig             loading config from /etc/fwupd/remotes.d/dell-esrt.conf
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0331 FuConfig             loading config from /etc/fwupd/remotes.d/lvfs.conf
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0331 FuConfig             loading config from /etc/fwupd/remotes.d/vendor.conf
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0331 FuConfig             using config path of /usr/lib/fwupd
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0331 FuConfig             path /usr/lib/fwupd/remotes.d does not exist
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0331 FuConfig             ordering lvfs-testing=lvfs+1
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0332 FuConfig             ignoring unfound remote fwupd
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0332 FuConfig             ignoring unfound remote fwupd
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0332 FuConfig             ::configuration changed
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 FuEngine             remote lvfs-testing not enabled, so skipping
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 FuEngine             remote fwupd-tests not enabled, so skipping
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 FuEngine             remote vendor not enabled, so skipping
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 FuEngine             remote vendor-directory not enabled, so skipping
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 XbSilo               attempting to load /var/cache/fwupd/metadata.xmlb
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 XbSilo               0.04ms      parse blob
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 XbSilo               0.10ms      loaded file
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 XbSilo               file: e156cc7d-cdee-59af-867a-f11b1b5ea7fd, current:e156cc7d-cdee-59af-867a-f11b1b5ea7fd, cached: (null)
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 XbSilo               loading silo with file contents
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0333 XbSilo               0.01ms      parse blob
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0334 XbSilo               0.42ms      query on / with `components/component` limit=0 -> 307 results
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0334 FuEngine             307 components now in silo
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0334 XbSilo               0.49ms      query on / with `components/component/provides/firmware` limit=0 -> 366 results
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0335 XbSilo               0.29ms      query on / with `components/component/provides/firmware` limit=0 -> 366 results
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0336 XbSilo               0.62ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='c7920601-0cda-507f-851e-92229eb1d370']/../..` limit=1 -> 1 results
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0336 XbSilo               0.63ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='230c8b18-8d9b-53ec-838b-6cfc0383493a']/../..` limit=1 -> 0 results
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0338 XbSilo               1.24ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='6986c21a-0f3f-5538-bcef-fe4e8cda7ab7']/../..|components/component/provides/firmware[@type='flashed'][text()='52aa8ac7-c837-561f-af32-b7979cd2f6ed']/../..` limit=1 -> 0 results
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0339 XbSilo               1.28ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='ff2112dc-038c-596d-90ca-d43c5077c6ec']/../..|components/component/provides/firmware[@type='flashed'][text()='63af1441-fb24-5368-b450-886fbc98610b']/../..` limit=1 -> 0 results
Oct 13 21:21:05 xXx fwupd[1791]: 03:21:05:0340 XbSilo               0.65ms      query on / with `components/component/provides/firmware[@type='flashed'][text()='9d131a0c-a606-580f-8eda-80587250b8d6']/../..|components/component/provides/firmware[@type='flashed'][text()='279ed287-3607-549e-bacc-f873bb9838c4']/../..` limit=1 -> 1 results
```

**Comment by in0ni** [comment] 2019-10-14 03:47
Thanks @superm1!

This and also enabling "Windows UEFI Firmware Update" (as shown in #856) in the BIOS did the trick
