### ISSUE TITLE
fwupd 1.8.8_1 x86_64 not found on any Repositories

### ISSUE THREAD

**Issue by samuel0r** [fwupd/fwupd#5377] opened 2023-01-04 11:31 UTC
**Describe the question**
fwupd 1.8.8-1 x86_64 tar.zst not found anywhere in fresh ArchLinux install 
**fwupd version information**
1.8.8_1 required to install desktop: plasma, gnome, xfce4

```shell
fwupdmgr --version
```
Tried with reflector setting 100 repositories.
Tried to install: pacman -S fwupd
Get the same error.
[fwupd-1.8.8-1.error.txt](https://github.com/fwupd/fwupd/files/10343650/fwupd-1.8.8-1.error.txt)

**Comment by hughsie** [comment] 2023-01-04 12:08
Dupe of https://github.com/fwupd/fwupd/issues/5376

**Closed by hughsie** 2023-01-04 12:08 UTC
Labels: question
