### ISSUE TITLE
Lenovo T490, Ubuntu 21.04, Boot Order Lock disabled: "failed to run update on reboot"

### ISSUE THREAD

**Issue by kees** [fwupd/fwupd#3395] opened 2021-06-18 17:00 UTC
**Describe the bug**
It seems UEFI updates are never running. Even if I manually select Linux-Firmware-Updater, normal boot continues. I'm at a loss for where to get further diagnostic details.

**Steps to Reproduce**
```shell
$ sudo fwupdmgr upgrade
$ sudo shutdown -r now
```
**Expected behavior**
Firmware updates run.

**fwupd version information**
Please provide the version of the daemon and client.
```shell
$ fwupdmgr --version
client version:	1.5.8
compile-time dependency versions
	gusb:	0.3.5

daemon version:	1.5.8
```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
apt:
```sh
$ dpkg -l fwupd | grep ^.i
ii  fwupd          1.5.8-0ubuntu1 amd64        Firmware update daemon
```

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```sh
$ fwupdmgr get-devices --show-all-devices
20N2001YUS
│
├─Thunderbolt host controller:
│     Device ID:          a804dbcfab80c29f688d74aa71a45052be0d2d73
│     Summary:            Unmatched performance for high-speed I/O
│     Current version:    20.00
│     Vendor:             Lenovo (THUNDERBOLT:0x0109|TBT:0x0109)
│     GUIDs:              dd092983-daaf-587a-9ed7-dd8d178adbe7
│                         abc4cc28-099d-5220-b45d-129c21cd9da7
│                         52265728-359a-574c-9a6a-a23d3b1f952d
│                         f117e89e-a75f-5f33-9e8e-c4aded9cbadf
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Device stages updates
│   
├─Embedded Controller:
│     Device ID:          489f23b2ba9c1adf3e9f9f10598c98ba5c6bba39
│     Current version:    0.1.23
│     Minimum Version:    0.1.23
│     Vendor:             DMI:LENOVO
│     GUIDs:              38ea6335-29ca-417b-8cd4-6b4e5e866f92
│                         78c6acda-f389-5111-839d-7f258cef874b
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel Management Engine:
│     Device ID:          b1c32d855d85a2124e865f0a03f8c2384dcca167
│     Current version:    192.72.1757
│     Minimum Version:    0.0.1
│     Vendor:             DMI:LENOVO
│     GUIDs:              bf2d0f8b-f9a9-400c-8914-36c225d16eb4
│                         f8f599da-ffda-570a-9c05-841037bd487a
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel(R) Core™ i5-8265U CPU @ 1.60GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000ea
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f
│                         30249f37-d140-5d3e-9319-186b1bd5cac3
│                         561403e8-143a-5071-ab09-bf5e4c146983
│                         d5092916-1868-5182-8c70-12f83dab6372
│     Device Flags:       • Internal device
│   
├─Prometheus:
│ │   Device ID:          d432baa2162a32c1554ef24bd8281953b9d07c11
│ │   Summary:            Fingerprint reader
│ │   Current version:    10.01.3273255
│ │   Vendor:             Synaptics (USB:0x06CB)
│ │   Install Duration:   2 seconds
│ │   GUIDs:              09e8bf16-3e69-50f5-bb66-c7a040248352
│ │                       8088f861-6318-5b1e-9ce4-fbddbedb09ac
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Cryptographic hash verification is available
│ │ 
│ └─Prometheus IOTA Config:
│       Device ID:        8dcffb5d059857368caa2b7b22371ebd831b0c0c
│       Current version:  0028
│       Minimum Version:  0028
│       Vendor:           Synaptics (USB:0x06CB)
│       GUIDs:            7c5a1e62-38fa-5859-9337-09dbac6377e4
│                         21a62213-7012-552c-9f1a-a51d07c87242
│       Device Flags:     • Updatable
│                         • Supported on remote server
│     
├─SAMSUNG MZVLB256HBHQ-000L7:
│     Device ID:          f2759da7fe8e0388c5f3601cb072f837b1070b03
│     Summary:            NVM Express Solid State Drive
│     Current version:    5M2QEXH7
│     Vendor:             Samsung Electronics Co Ltd (NVME:0x144D)
│     GUIDs:              0b4d773a-7ac3-58c1-a541-e22ef1cdfe02
│                         c9d531ea-ee7d-5562-8def-c64d0d144813
│                         6e54c992-d302-59ab-b454-2d26ddd63e6d
│                         47335265-a509-51f7-841e-1c94911af66b
│                         1b3b43f9-e0b0-5978-a89b-6f0866124233
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          6150dd1f7291b0709289ab8a53cc85a17e117ef2
│ │   Current version:    0.1.71
│ │   Minimum Version:    0.0.1
│ │   Vendor:             LENOVO (DMI:LENOVO)
│ │   Update State:       Success
│ │   GUIDs:              603baf73-b997-45b5-86b4-2f981a008e18
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       ad36afa7-70a6-59e5-a6b4-ccccfb15d50f
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI Revocation Database
│       Current version:  238
│       Minimum Version:  238
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            14503b3d-73ce-5d06-8137-77c68972a341
│                         5971a208-da00-5fce-b5f5-1234342f9cf7
│                         c6682ade-b5ec-57c4-b687-676351208742
│                         f8ba2887-9411-5c36-9cee-88995bb39731
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│     
├─TPM:
│ │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Current version:    7.2.1.0
│ │   Vendor:             Nuvoton Technology (TPM:NTC)
│ │   GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6
│ │                       fac1c8f3-73c8-5cd6-8330-07a3690b5140
│ │                       8d94eb9a-78aa-513d-af50-319e3b9f5210
│ │                       e9ccc1dc-960a-5e09-afe9-e59a904b776d
│ │                       f1c4013d-3f4c-5623-a40b-81ad96e23860
│ │   Device Flags:       • Internal device
│ │ 
│ └─Event Log:
│       Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
│       GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff
│       Device Flags:     • Internal device
│     
├─UEFI Device Firmware:
│     Device ID:          98a394c65d64ece8aae3126fb0f85364bb915b49
│     Current version:    16842768
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     GUIDs:              25dd5a7f-4151-401f-ae35-1440807c7bba
│                         640d2cce-1a3d-5f22-8e01-0d4fdcb52f88
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          f60653d31d92c3e457bf7e5606fe7dda211b72d4
│     Current version:    117571840
│     Minimum Version:    117571840
│     Vendor:             DMI:LENOVO
│     GUIDs:              bb667386-6ec6-4d32-bb8c-5183a6cc2c95
│                         cd1038ca-528d-5dc1-96af-9231a65b4baf
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
└─UHD Graphics 620 (Whiskey Lake):
      Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
      Current version:    02
      Vendor:             Intel Corporation (PCI:0x8086)
      GUIDs:              66cc0948-6f3b-5d92-9277-ae69a2ec6ec7
                          5461564d-d717-53e3-95c6-706973f9245d
                          6986c21a-0f3f-5538-bcef-fe4e8cda7ab7
                          52aa8ac7-c837-561f-af32-b7979cd2f6ed
      Device Flags:       • Internal device
                          • Cryptographic hash verification is available
```

```sh
$ fwupdmgr get-history
20N2001YUS
│
└─System Firmware:
  │   Device ID:          6150dd1f7291b0709289ab8a53cc85a17e117ef2
  │   Previous version:   0.1.71
  │   Update State:       Failed
  │   Update Error:       failed to run update on reboot
  │   Last modified:      2021-06-18 16:27
  │   GUID:               603baf73-b997-45b5-86b4-2f981a008e18
  │   Device Flags:       • Internal device
  │                       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Needs a reboot after installation
  │                       • Reported to remote server
  │                       • Cryptographic hash verification is available
  │                       • Device is usable for the duration of the update
  │ 
  └─ThinkPad T490/ThinkPad P43s/ThinkPad T590/ThinkPad P53s/ThinkPad T490 HC (W-BIOS for Machine types: 20N2, 20N3, 20N4, 20N5, 20N6, 20N7, 20Q9, 20QH, 20RH, 20RJ) System Update:
        New version:      0.1.73
        Remote ID:        lvfs
        Summary:          Lenovo ThinkPad T490/ThinkPad P43s/ThinkPad T590/ThinkPad P53s/ThinkPad T490 HC System Firmware
        License:          Proprietary
        Size:             25.1 MB
        Created:          2020-01-10
        Urgency:          High
        Vendor:           Lenovo Ltd.
        Flags:            is-upgrade
        Description:      
        Lenovo ThinkPad T490 P43s T590 P53s T490 HC (W-BIOS) System Firmware 1.73
        
        The computer will be restarted automatically after updating BIOS completely. Do NOT turn off your computer or remove the AC adaptor while update is in progress.
        
        This stable release fixes the following issues:
        
        • Fixed an issue where system might hang when external USB keyboard is connected
        
        and Kernel DMA is set to Enabled by ThinkPad Setup.
        
        Some new functionality has also been added:
        
        • Updated the CPU microcode.
      
```

**System UEFI configuration**
Please provide the output of the following commands:
```sh
$ efibootmgr -v
BootCurrent: 0001
Timeout: 0 seconds
BootOrder: 0001,0000,0010,0011,0012,0013,0014,0015,0019,001A,001B,001C,001D,001E,001F,0020,0021,0022,0023,0002
Boot0000* Windows Boot Manager	HD(1,GPT,63f0c932-2841-4fbd-89fc-f401c3b488f2,0x800,0x82000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}....................
Boot0001* ubuntu	HD(1,GPT,63f0c932-2841-4fbd-89fc-f401c3b488f2,0x800,0x82000)/File(\EFI\ubuntu\shimx64.efi)
Boot0002* Linux-Firmware-Updater	HD(1,GPT,63f0c932-2841-4fbd-89fc-f401c3b488f2,0x800,0x82000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.d.x.6.4...e.f.i...
Boot0010  Setup	FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu	FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen	FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics	FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  Regulatory Information	FvFile(478c92a0-2622-42b7-a65d-5894169e4d24)
Boot0015  ThinkShield secure wipe	FvFile(3593a0d5-bd52-43a0-808e-cbff5ece2477)
Boot0016  Startup Interrupt Menu	FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0017  Rescue and Recovery	FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0018  MEBx Hot Key	FvFile(ac6fd56a-3d41-4efd-a1b9-870293811a28)
Boot0019* USB CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot001A* USB FDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot001B* NVMe0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001C* NVMe1	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a401)
Boot001D* ATA HDD0	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f602)
Boot001E* ATA HDD1	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f601)
Boot001F* USB HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot0020* PXE BOOT	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot0021* LENOVO CLOUD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,ad38ccbbf7edf04d959cf42aa74d3650)/Uri(https://download.lenovo.com/pccbbs/cdeploy/efi/boot.efi)
Boot0022  Other CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a35406)
Boot0023  Other HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f606)
Boot0024* IDER BOOT CDROM	PciRoot(0x0)/Pci(0x14,0x0)/USB(11,1)
Boot0025* IDER BOOT Floppy	PciRoot(0x0)/Pci(0x14,0x0)/USB(11,0)
Boot0026* ATA HDD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f6)
Boot0027* ATAPI CD	VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a354)
```

```sh
$ efivar -l | grep fw
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-603baf73-b997-45b5-86b4-2f981a008e18-0
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-ux-capsule
```

```sh
$ sudo tree /boot/efi/EFI/{boot,ubuntu}
/boot/efi/EFI/boot
├── bootx64.efi
├── fbx64.efi
├── LenovoBT.EFI
├── License.txt
├── mmx64.efi
└── ReadMe.txt
/boot/efi/EFI/ubuntu
├── BOOTX64.CSV
├── fw
│   ├── fwupd-3b8c8162-188c-46a4-aec9-be43f1d65697.cap
│   └── fwupd-603baf73-b997-45b5-86b4-2f981a008e18.cap
├── fwupdx64.efi
├── grub.cfg
├── grubx64.efi
├── mmx64.efi
└── shimx64.efi

1 directory, 14 files
```

**Additional questions**
- Operating system and version:
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```
- Have you tried rebooting?
A lot. ;)

- Is this a regression?
Yes, but I'm not sure when it started. I'm at least two firmware versions behind currently.

- Are you using an NVMe disk?
Yes.

- Is secure boot enabled?
Yes

- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS?
It is a Lenovo, but "Boot Order Lock" is disabled.

**Comment by superm1** [comment] 2021-06-18 17:21
It is a shim bug in newer distros (like Ubuntu 21.04): https://bugs.launchpad.net/ubuntu/+source/shim/+bug/1929471

You can turn off secure boot to do the update and it should help the situation.

**Comment by superm1** [comment] 2021-06-18 17:22
duplicate of https://github.com/fwupd/firmware-lenovo-thinkpad/issues/123

**Closed by superm1** 2021-06-18 17:22 UTC
Labels: bug, duplicate

**Comment by kees** [comment] 2021-06-18 19:01
Ah! Thanks for the pointer. Yes, if I add a manual UEFI entry for fwupdx64.efi and turn off secure boot, things worked correctly. Hopefully https://github.com/rhboot/shim/pull/379 will fix it?

**Comment by superm1** [comment] 2021-06-28 14:24
Hopefully, that or https://github.com/rhboot/shim/pull/381
