### ISSUE TITLE
Failed to get devices when Dell HD22Q Docking was plugged

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [fwupd/fwupd#6578] opened 2023-12-28 02:08 UTC
**Describe the bug**
Failed to get devices when Dell HD22Q was plugged after upgrade fwupd to 1.9.10.

Dec 28 09:42:59 202002-27723 systemd[1]: Starting Firmware update daemon...
Dec 28 09:43:00 202002-27723 fwupd[2984]: 01:43:00.980 FuEngine             failed to add device usb:04:00:01:04:03: No device GType set
Dec 28 09:43:17 202002-27723 fwupd[2984]: 01:43:17.586 FuEngine             failed to add device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-4/drm_dp_aux4: failed to add device using on synaptics_mst: failed to enable remote control: remote command failed: invalid [1]
Dec 28 09:43:19 202002-27723 fwupd[2984]: 01:43:19.712 FuMain               Daemon ready for requests (locale en_US.UTF-8)
Dec 28 09:43:22 202002-27723 systemd[1]: Started Firmware update daemon.

**Steps to Reproduce**
Run command
$ sudo fwupdtool get-devices --verbose

**Expected behavior**
Can get devices successfully without error.

**fwupd version information**
compile   com.hughsie.libxmlb           0.3.6
compile   com.hughsie.libjcat           0.1.9
compile   org.freedesktop.fwupd         1.9.10
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.3.10
runtime   org.freedesktop.gusb          0.3.10
runtime   org.freedesktop.fwupd         1.9.10
runtime   org.kernel                    6.2.0-39-generic

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
I install it on Ubuntu 22.04, and utilize ppa to create 1.9.10 fwupd packages.
$ sudo add-apt-repository ppa:kchsieh/fwupd
$ sudo apt install fwupd

<details>

<summary>**fwupd device information**</summary>
Dell Inc. Precision 5750
│
├─DELL0990:00 04F3:311C:
│     Device ID:          b8cfad8dcc60878190ea039a952b3d7cd97cad91
│     Summary:            Touchpad
│     Current version:    0x000a
│     Bootloader Version: 0x0001
│     Vendor:             ELAN Microelectronics (HIDRAW:0x04F3)
│     GUIDs:              46598f8d-5777-50c4-8da9-cda0cc8bbc26 ← HIDRAW\VEN_04F3&DEV_311C
│                         d00322f0-ff1f-5458-9c64-8a771fb0b72e ← HIDRAW\VEN_04F3&DEV_311C&MOD_0000
│                         6cf7ae6a-8b98-5b63-9af8-b23b932f65de ← ELANTP\ICTYPE_13&MOD_0000
│                         ac3627a9-8463-5e63-b6b1-be9e0bcf27d2 ← ELANTP\ICTYPE_13&MOD_0000&DRIVER_HID
│     Device Flags:       • Internal device
│                         • Updatable
│     Device Requests:    • Message
│                         • Image
│   
├─HD22Q:
│ │   Device ID:          495a64cd518871c4511a85022df727c538ef67ba
│ │   Summary:            High performance dock
│ │   Current version:    01.00.00.03
│ │   Vendor:             Dell Inc. (USB:0x413C)
│ │   Install Duration:   1 minute
│ │   Serial Number:      8L281L3/3110746456619804
│ │   GUID:               67de0057-2f75-5bea-a388-ced11251dd78 ← USB\VID_413C&PID_B06E&hub&atomic_embedded
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │   Device Requests:    • Image
│ │ 
│ ├─Package level of Dell dock:
│ │     Device ID:        2a1e7ab23626ef9e1e5407b45605680dbc982939
│ │     Summary:          A representation of dock update status
│ │     Current version:  01.00.11.01
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 5 seconds
│ │     GUIDs:            7fd6ce60-8243-59b6-a814-a02c2d501940
│ │                       fc7c6f01-9d2a-5bb5-89eb-59542fb93c46 ← USB\VID_413C&PID_B06E&hub&atomic_status
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device can recover flash failures
│ │                       • Device is usable for the duration of the update
│ │                       • Unsigned Payload
│ │     Device Requests:  • Image
│ │   
│ ├─RTS5413 in Dell dock:
│ │     Device ID:        7a5579e81fd66cf89c04f697e139ff5abb213dd8
│ │     Summary:          USB 3.1 Generation 1 Hub
│ │     Current version:  01.51
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 14 seconds
│ │     GUIDs:            b27d25f1-019d-5718-b41a-02ddaefe5577 ← USB\VID_413C&PID_B06F
│ │                       d6d59be5-b1a7-57f9-9319-bc315a816bf2 ← USB\VID_413C&PID_B06F&atomic_hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │     Device Requests:  • Image
│ │   
│ ├─RTS5487 in Dell dock:
│ │     Device ID:        0281bab136df92eb4cb0f77f1a334296da0ce36d
│ │     Summary:          USB 3.1 Generation 2 Hub
│ │     Current version:  01.55
│ │     Vendor:           Dell Inc. (USB:0x413C)
│ │     Install Duration: 3 seconds
│ │     GUIDs:            acfcd89b-105d-55b9-b85b-08bf8508f38c ← USB\VID_413C&PID_B06E
│ │                       7a9e5b3a-c2e7-5eb7-9b0a-afa9993aded0 ← USB\VID_413C&PID_B06E&atomic_hub
│ │     Device Flags:     • Updatable
│ │                       • Supported on remote server
│ │                       • Device stages updates
│ │                       • Device is usable for the duration of the update
│ │                       • Signed Payload
│ │     Device Requests:  • Image
│ │   
│ └─VMM6210 in Dell dock:
│       Device ID:        31560cc63bc26c86e1b2b8b8eecdff17209beccd
│       Summary:          Multi Stream Transport controller
│       Current version:  06.05.01
│       Vendor:           Dell Inc. (USB:0x413C)
│       Install Duration: 6 minutes
│       GUID:             0d1dd733-a180-5739-82b5-e634a3993e2d ← MST-cayenne-vmm6210-257
│       Device Flags:     • Updatable
│                         • Supported on remote server
│                         • Device stages updates
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│       Device Requests:  • Image
│     
├─Unknown Device:
│     Device ID:          601d9aa566c72d316cf20ecacf7cacbed249d807
│     Serial Number:      PAM04565SL0
│     GUID:               9a62346d-3c50-5d41-abf7-530a81c3b999 ← DRM\VEN_BNQ&DEV_7949
│   
├─Unknown Device:
│     Device ID:          4a4907dbb1b96c6a1177dfd1b95eb41c781d1265
│     GUID:               1199a818-4c52-5137-b536-d59e2e2cada9 ← GPIO\ID_INT3450:00
│   
├─7JXK8:
│     Device ID:          10feb8f8641be9b4f44d52078baa6338209a53ef
│     GUID:               397dd42a-630f-5e07-8335-eb1fc9d95613 ← DRM\VEN_SHP&DEV_14D6
│     Device Flags:       • Internal device
│     Device Requests:    • Message
│   
├─Display controller:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    05
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              d2a76018-8fff-5e3e-a424-fa814e8c04fc ← PCI\VEN_8086&DEV_9BF6
│                         74e28e03-cf7c-59b2-81d2-e6781ddd6141 ← PCI\VEN_8086&DEV_9BF6&SUBSYS_10280990
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│     Device Requests:    • Message
│   
├─Integrated Webcam HD:
│     Device ID:          b6bcdb236926a2452b472d3dad455c414145b52e
│     Current version:    91.79
│     Vendor:             CN02FP438LG009BPB09CX04 (USB:0x0BDA)
│     Serial Number:      200901010001
│     GUID:               468fbb8a-10ee-5262-af12-dac8eb7b0087 ← USB\VID_0BDA&PID_5510
│     Device Flags:       • Updatable
│     Device Requests:    • Image
│   
├─KXG60ZNV1T02 NVMe TOSHIBA 1024GB:
│     Device ID:          03281da317dccd2b18de2bd1cc70a782df40ed7e
│     Summary:            NVM Express solid state drive
│     Current version:    10604107
│     Vendor:             Toshiba Corporation (NVME:0x1179)
│     Serial Number:      19QS10EHTHEQ
│     GUIDs:              8a412b95-5c07-5ce4-b63a-f9cbf254dd5d ← STORAGE-DELL-107443
│                         344c2804-4948-e811-842f-0ed5f89f718b
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─Pixel USB-C earbuds:
│     Device ID:          0fef0a0c55f6442bffaebd774ae771341c89571b
│     Summary:            CX21986 USB audio device
│     Current version:    47-85-14
│     Bootloader Version: 03.01.00.00
│     Vendor:             Google (USB:0x18D1)
│     Install Duration:   3 seconds
│     Serial Number:      0
│     GUID:               93279fe8-d478-531b-9637-05d026be3c2e ← USB\VID_18D1&PID_5033
│     Device Flags:       • Updatable
│                         • Unsigned Payload
│     Device Requests:    • Image
│   
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    1.27.1
│ │   Minimum Version:    1.27.1
│ │   Vendor:             Dell (DMI:Dell Inc.)
│ │   Update State:       Success
│ │   GUID:               7d606caf-92d8-47ad-9400-77ec5326af68
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │   Device Requests:    • Message
│ │                       • Image
│ │                       • Image (custom)
│ │ 
│ ├─AMT [unprovisioned]:
│ │     Device ID:        8d5470e73fd9a31eaa460b2b6aea95483fe3f14c
│ │     Summary:          Hardware and firmware technology for remote out-of-band management
│ │     Current version:  14.1.70.2228
│ │     Bootloader Version:14.1.70.2228
│ │     Vendor:           Intel Corporation (MEI:0x8086)
│ │     GUIDs:            12f80028-b4b7-4b2d-aca8-46e0ff65814c
│ │                       15c7ef4d-12fc-5e25-aba6-49b30f5ab130 ← MEI\VEN_8086&DEV_06E0
│ │                       60633a6d-e291-5b5f-88fc-3933f832ee75 ← MEI\VEN_8086&DEV_06E0&SUBSYS_10280990
│ │     Device Flags:     • Internal device
│ │     Device Requests:  • Message
│ │   
│ ├─BootGuard Configuration:
│ │     Device ID:        b0d4430dfa6bde9f0c22680df36dbc8c15c80753
│ │     Vendor:           Intel Corporation (MEI:0x8086)
│ │     GUIDs:            dd17041c-09ea-4b17-a271-5b989867ec65
│ │                       15c7ef4d-12fc-5e25-aba6-49b30f5ab130 ← MEI\VEN_8086&DEV_06E0
│ │                       60633a6d-e291-5b5f-88fc-3933f832ee75 ← MEI\VEN_8086&DEV_06E0&SUBSYS_10280990
│ │     Device Flags:     • Internal device
│ │     Device Requests:  • Message
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  371
│       Minimum Version:  371
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            4a6cd2cb-8741-5257-9d1f-89a275dacca7 ← UEFI\CRT_E28D59CA489BD2AD580F2EA5D62D6A29BB9C02AE5A818434A37DA7FC11DFF9E9&ARCH_X64
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Only version upgrades are allowed
│                         • Signed Payload
│       Device Requests:  • Message
│                         • Image
│     
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Current version:    1.257.0.0
│     Vendor:             ST Microelectronics (TPM:STM)
│     GUIDs:              84df3581-f896-54d2-bd1a-372602f04c32 ← TPM\VEN_STM&DEV_0001
│                         bfaed10a-bbc1-525b-a329-35da2f63e918 ← TPM\VEN_STM&MOD_
│                         70b7b833-7e1a-550a-a291-b94a12d0f319 ← TPM\VEN_STM&DEV_0001&VER_2.0
│                         06f005e9-cb62-5d1a-82d9-13c534c53c48 ← TPM\VEN_STM&MOD_&VER_2.0
│                         5dcb361a-4d48-5347-80a8-90de4337aaf4 ← 0990-2.0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device can recover flash failures
│                         • Full disk encryption secrets may be invalidated when updating
│                         • Signed Payload
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─TU117GLM [Quadro T2000 Mobile / Max-Q]:
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a1
│     Vendor:             NVIDIA Corporation (PCI:0x10DE, PCI:0x8086)
│     GUIDs:              32757a2c-105b-5e6c-9566-cd704c90f081 ← PCI\VEN_10DE&DEV_1FB8
│                         f32d2e48-eb11-5e13-9076-ccee95454f0a ← PCI\VEN_10DE&DEV_1FB8&SUBSYS_10280990
│                         d29269b6-e458-5f45-975c-9d52bb38e35f ← PCI\VEN_8086&DEV_1901
│                         c4153a86-8224-5dad-aacf-cbccb7714704 ← PCI\VEN_8086&DEV_1901&SUBSYS_10280990
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│     Device Requests:    • Message
│   
├─Thunderbolt host controller:
│     Device ID:          ac837f092388d22a5c71778eec620788aad44864
│     Summary:            Unmatched performance for high-speed I/O
│     Current version:    56.00
│     Vendor:             Dell (THUNDERBOLT:0x00D4, TBT:0x00D4)
│     GUIDs:              44e42752-0136-5e98-812e-7a7e2c876b3e ← THUNDERBOLT\VEN_00D4&DEV_0990
│                         cd8d2b1e-ca51-5649-87ad-d3cbe54483c6 ← TBT-00d40990-native
│                         b690ada5-1737-5838-8992-044b771e92b9 ← TBT-00d40990-native-controller0-0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Device stages updates
│                         • Signed Payload
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─Thunderbolt host controller:
│     Device ID:          47edbcd95eabc324006537330cf465794011f7ae
│     Summary:            Unmatched performance for high-speed I/O
│     Current version:    56.00
│     Vendor:             Dell (THUNDERBOLT:0x00D4, TBT:0x00D4)
│     GUIDs:              44e42752-0136-5e98-812e-7a7e2c876b3e ← THUNDERBOLT\VEN_00D4&DEV_0990
│                         cd8d2b1e-ca51-5649-87ad-d3cbe54483c6 ← TBT-00d40990-native
│                         3bc8a4b3-0042-53f6-aaab-e1dc3db80b22 ← TBT-00d40990-native-controller1-0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Device stages updates
│                         • Signed Payload
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    248
│     Minimum Version:    248
│     Vendor:             DMI:Dell Inc.
│     Update State:       Success
│     GUID:               ffd6eef5-4372-4adc-8eeb-3dc0b7338375
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─UEFI Device Firmware:
│     Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
│     Summary:            UEFI ESRT device
│     Current version:    274743559
│     Minimum Version:    274743559
│     Vendor:             DMI:Dell Inc.
│     Update State:       Success
│     GUID:               344c2804-4948-e811-842f-0ed5f89f718b
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│     Device Requests:    • Message
│                         • Image
│                         • Image (custom)
│   
├─UEFI Platform Key:
│     Device ID:          6924110cde4fa051bfdc600a60620dc7aa9d3c6a
│     Summary:            Dell Inc. Platform Key
│     Vendor:             Dell Inc.
│     GUID:               5f7cc4ea-9f7a-5c5f-b535-dfbcc73f5ba6 ← UEFI\CRT_2493B118EABD632FD3BA49C333A8329B1982E872
│   
└─Xeon W-10855M CPU @ 2.80GHz:
      Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
      Current version:    0x000000f8
      Vendor:             Intel
      GUIDs:              a45b0522-5722-54bd-b802-86cd044262df ← CPUID\PRO_0&FAM_06&MOD_A5
                          7b9b6e8c-226c-5db6-86cb-ea3187578013 ← CPUID\PRO_0&FAM_06&MOD_A5&STP_2
      Device Flags:       • Internal device
      Device Requests:    • Message
    

</details>

**Additional questions**

- Operating system and version:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
- Have you tried rebooting?
coldboot warmboot can both reproduce the issue
- Is this a regression?
yes

**Comment by superm1** [comment] 2023-12-30 20:07
Can you please provide output for

`sudo fwupdtool get-devices -vv`

@CragW ∆

**Comment by superm1** [comment] 2023-12-30 20:08
Can  you please reproduce on 1_9_X branch? We've had some changes to synaptics mst plugin for Cayenne support which is listed here in your output which isn't yet tagged into a new release.

**Comment by CragW** [comment] 2023-12-31 00:49
> Can you please provide output for
> 
> `sudo fwupdtool get-devices -vv`
> 
> @CragW ∆

Sure, will check on Tue. Was out for a family event.

**Comment by superm1** [comment] 2024-01-01 18:33
I was thinking more about this issue; and _perhaps_ the actual issue is that the `dell_dock` plugin and the `synaptics_mst` plugin are both touching the same hardware.  We used to have a way to prevent Synaptics MST from probing stuff in a Dell Dock since the `dell_dock` plugin was the preferred update method. 

To prove if this is the case; you can try to blacklist the `dell_dock` plugin in the `DisabledPlugins` key in `/etc/fwupd/fwupd.conf`.  
* If that helps then I think we need a way to block the MST hub in this dock from probing in the synaptics MST plugin. 
* If this doesn't help; it's a different root cause.  It could be something to do with the host hardware containing a Synaptics MST hub or the monitor being connected containing one.  It could even be exposing a kernel driver MST bug.  You might look at kernel log with drm.debug output turned up while running `fwupd` or `fwupdtool` enumerate for hints.

**Comment by CragW** [comment] 2024-01-02 03:21
> Dec 28 09:43:00 202002-27723 fwupd[2984]: 01:43:00.980 FuEngine failed to add device usb:04:00:01:04:03: No device GType set

@superm1  We can remove `Realtek NIC` device from dell.quirk to address this error.

> Dec 28 09:43:17 202002-27723 fwupd[2984]: 01:43:17.586 FuEngine failed to add device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-4/drm_dp_aux4: failed to add device using on synaptics_mst: failed to enable remote control: remote command failed: invalid [1]

`dell_dock` plugin doesn't use `drm_dp_aux`;  This error is introduced by `synaptics_mst` itself trying to enable remote control, maybe handle the error in a nicer way.

**Comment by superm1** [comment] 2024-01-02 03:43
> > Dec 28 09:43:00 202002-27723 fwupd[2984]: 01:43:00.980 FuEngine failed to add device usb:04:00:01:04:03: No device GType set
> 
> @superm1  We can remove `Realtek NIC` device from dell.quirk to address this error.
> 
> > Dec 28 09:43:17 202002-27723 fwupd[2984]: 01:43:17.586 FuEngine failed to add device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-4/drm_dp_aux4: failed to add device using on synaptics_mst: failed to enable remote control: remote command failed: invalid [1]
> 
> `dell_dock` plugin doesn't use `drm_dp_aux`;  This error is introduced by `synaptics_mst` itself trying to enable remote control, maybe handle the error in a nicer way.
> 

But if it's the same physical device and Dell dock enabled remote control already it might cause this kind of failure is my theory.

The verbose log and the experiment I suggested should confirm it.

**Comment by CragW** [comment] 2024-01-02 04:00
I've disabled `dell_dock` plugin, the error generated by `synaptcis_mst` happens anyway regardless dock, see:
[no_dell_dock_plugin.txt](https://github.com/fwupd/fwupd/files/13807035/no_dell_dock_plugin.txt)

```
03:53:17.858 FuEngine             plugins disabled: dell_dock, test, test_ble
...

03:53:18.405 FuEngine             failed to add device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-6/drm_dp_aux6: failed to add device using on synaptics_mst: failed to enable remote control: remote command failed: invalid [1]
```

**Comment by superm1** [comment] 2024-01-02 04:15
> I've disabled `dell_dock` plugin, the error generated by `synaptcis_mst` happens anyway regardless dock, see: [no_dell_dock_plugin.txt](https://github.com/fwupd/fwupd/files/13807035/no_dell_dock_plugin.txt)
> 
> ```
> 03:53:17.858 FuEngine             plugins disabled: dell_dock, test, test_ble
> ...
> 
> 03:53:18.405 FuEngine             failed to add device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-6/drm_dp_aux6: failed to add device using on synaptics_mst: failed to enable remote control: remote command failed: invalid [1]
> ```

Is that even with a power cycled dock?

**Comment by superm1** [comment] 2024-01-02 04:17
@CloudExt can you please look at this?

**Comment by superm1** [comment] 2024-01-02 04:23
Something funky to me is that multiple dp aux devices have the exact same DPCD:
```
03:53:18.045 FuDevice             using d762543f8c20f636e6fff031a000078d3e10c600 for PCI_SLOT_NAME=0000:00:02.0:drm_dp_aux1
03:53:18.046 FuDpauxDevice        DPAUX read @0x500:90 cc 24 53 59 4e 41 62 11 10 06 05 00 
03:53:18.046 FuStruct             DpauxDpcd:
  ieee_oui: 0x90cc24
  dev_id: SYNAb.
  hw_rev: 0x10
  fw_ver: 0x60500
03:53:18.046 FuDevice             using 585c346c009da3cc19a400fb59a4ed8d0cbd0151 for PCI_SLOT_NAME=0000:00:02.0:drm_dp_aux2
03:53:18.067 FuBackend            failed to open device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-2/drm_dp_aux2: DPCD read failed: failed to read 14: No such device or address
03:53:18.068 FuDevice             using 2d9bd19a73af0e1160733d42c55f1d9de90ed451 for PCI_SLOT_NAME=0000:00:02.0:drm_dp_aux3
03:53:18.089 FuBackend            failed to open device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-3/drm_dp_aux3: DPCD read failed: failed to read 14: No such device or address
03:53:18.089 FuDevice             using cd3818e2d3a168ec7e137e21fdfb21df5ad2e175 for PCI_SLOT_NAME=0000:00:02.0:drm_dp_aux4
03:53:18.110 FuBackend            failed to open device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-4/drm_dp_aux4: DPCD read failed: failed to read 14: No such device or address
03:53:18.111 FuDevice             using 47a0754f6a2c9a7eb5f2883e4b78834a64451577 for PCI_SLOT_NAME=0000:00:02.0:drm_dp_aux5
03:53:18.148 FuBackend            failed to open device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-5/drm_dp_aux5: DPCD read failed: failed to read 14: Input/output error
03:53:18.148 FuDevice             using d7bfd19a68de57bb7de8a0cc8f7b97680677abc4 for PCI_SLOT_NAME=0000:00:02.0:drm_dp_aux6
03:53:18.185 FuDpauxDevice        DPAUX read @0x500:90 cc 24 53 59 4e 41 62 11 10 06 05 00 
03:53:18.185 FuStruct             DpauxDpcd:
  ieee_oui: 0x90cc24
  dev_id: SYNAb.
  hw_rev: 0x10
  fw_ver: 0x60500
03:53:18.186 FuDevice             using a4d90c62862392b0f200f174dfb874c27bbbe86c for PCI_SLOT_NAME=0000:00:02.0:drm_dp_aux7
03:53:18.224 FuDpauxDevice        DPAUX read @0x500:00 00 00 00 00 00 00 00 00 00 00 00 00 
03:53:18.224 FuStruct             DpauxDpcd:
  ieee_oui: 0x0
  hw_rev: 0x0
  fw_ver: 0x0
```

I expected only one aux end point to have that DPCD.  It showing up on multiple is odd to me.  In the topology connected how many Synaptics MST hubs are really there?

Can this reproduce on a system that uses `amdgpu` instead of `i915`?

**Comment by superm1** [comment] 2024-01-02 04:24
> @superm1 We can remove `Realtek NIC` device from dell.quirk to address this error.
> 
> >

go ahead and follow up with a PR for this

**Comment by CragW** [comment] 2024-01-02 04:26
> > I've disabled `dell_dock` plugin, the error generated by `synaptcis_mst` happens anyway regardless dock, see: [no_dell_dock_plugin.txt](https://github.com/fwupd/fwupd/files/13807035/no_dell_dock_plugin.txt)
> > ```
> > 03:53:17.858 FuEngine             plugins disabled: dell_dock, test, test_ble
> > ...
> > 
> > 03:53:18.405 FuEngine             failed to add device /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-6/drm_dp_aux6: failed to add device using on synaptics_mst: failed to enable remote control: remote command failed: invalid [1]
> > ```
> 
> Is that even with a power cycled dock?

Yup, even with a new powered dock.

**Comment by CloudExt** [comment] 2024-01-02 08:09
How about just remove DELL docks in `synaptics-mst.quirk`?

**Comment by CloudExt** [comment] 2024-01-02 14:19
I think `synaptics_mst` uses DP aux and `dell_dock` on HID, I have no idea why the error occurred even two plugins touched the same device, the RC commands should work even you touched with different protocol at the same time.
Does any modification in `dp_aux` causes this issue?

@CragW Would it work when you disable `synaptics_mst` plugin?

**Comment by superm1** [comment] 2024-01-02 14:21
I notice in the [kernel source](https://github.com/torvalds/linux/blob/610a9b8f49fbcf1100716370d3b5f6f884a2835a/drivers/gpu/drm/display/drm_dp_mst_topology.c#L2315) that when a port is _added_ for MST it's given the name `DPMST`.

Considering this I think it's not really a new hub, but it's a given port that happens to be created downstream which happens to have the exact same DPCD.

A simple solution to this issue would be for the daemon to skip any aux devices with the name `DPMST`, but I suspect this also breaks anything actually cascaded.

**Comment by hughsie** [comment] 2024-01-02 14:34
> for the daemon to skip any aux devices with the name DPMST

I think that scuppers some of the plans we have for the future...

**Comment by superm1** [comment] 2024-01-02 14:38
> > for the daemon to skip any aux devices with the name DPMST
> 
> I think that scuppers some of the plans we have for the future...

I _think_ this should help: https://github.com/fwupd/fwupd/pull/6593.  Can still do downstream devices, but it won't fail if they're not really there.

**Comment by superm1** [comment] 2024-01-02 15:53
Hopefully this is fixed in both `main` and `1_9_X` branches now.  Please recheck.

**Comment by CragW** [comment] 2024-01-03 16:35
Issue still there by the build from source at 36ae23df8.

[synaptics_mst_enable_rc_invalid.log](https://github.com/fwupd/fwupd/files/13821330/synaptics_mst_enable_rc_invalid.log)

**Comment by superm1** [comment] 2024-01-03 16:40
That's unfortunate. Perhaps setting of the name by fu-udev-device isn't actually working. Can you dig into it?

**Comment by superm1** [comment] 2024-01-03 16:59
How about if you blacklist mediatek scalar plugin - does it keep happening?

**Comment by superm1** [comment] 2024-01-03 17:04
Maybe https://github.com/fwupd/fwupd/pull/6602 helps?

**Comment by CragW** [comment] 2024-01-04 13:00
> How about if you blacklist mediatek scalar plugin - does it keep happening?

The error persists; Also `$fwupdtool --plugins synaptics_mst get-devices` alone does see the error.

**Comment by superm1** [comment] 2024-01-04 13:10
> fwupdtool --plugins synaptics_mst get-devices

Can we see updated log for this for any other ideas?

**Comment by CragW** [comment] 2024-01-04 13:12
> Maybe #6602 helps?

Unfortunatelly no. 


> Perhaps setting of the name by fu-udev-device isn't actually working. Can you dig into it?

The device name is yet settled so `DPMST` didn't hit.

Just out of curiousity since the plugin attempts to try dpaux anyway why a test on `enable_rc` command introduces a critical error? I would expect to downgrade the error level as unsupported.

[fwupdtool-synaptics-mst-plugin-only.log](https://github.com/fwupd/fwupd/files/13830130/fwupdtool-synaptics-mst-plugin-only.log)

**Closed** 2024-01-05 12:33 UTC
Labels: bug
