### ISSUE TITLE
8BitDo SF30Pro testing upgrade v1.32 works but reports "USB error on device" 

### ISSUE THREAD

**Issue by herochao** [fwupd/fwupd#1529] opened 2019-11-04 09:45 UTC
Hello,
I just enabled the Testing LVFS repo to update my new SF30Pro to version 1.32 (v1.31->v1.32).

The update proceeded as normal but at the very end, the device reported to be disconnected, the controller apparently restarting in "Switch Mode". When reconnecting it in "Android Mode" and checking for firmware, I was prompted to submit a debug report (which I did), but the controller afterwards reported to be on version 1.32 and seemingly worked as usual.

This is really not an issue for me, but it might be interesting for you and provides testing for that particular update path.

Thank you for the great project and have a nice day!

update-output:
```
Upgrade available for 8Bitdo from 1.31 to 1.32
Downloading 1.32 for 8Bitdo...
Entpacken …              [***************************************]
Authentifizierung …      [***************************************]
8Bitdo wird aktualisiert … -                                     ]
Schreiben …              [***************************************] Weniger als eine Minute verbleiben…
USB error on device 2dc8:5750 : No such device (it may have been disconnected) [-4]
```

To help us pinpoint your issue, please insert the output of the
following commands when ran on the system with the issue:

```shell
$ fwupdmgr --version
client version:	1.3.3
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
daemon version:	1.3.3
```

Note, the switch `--version` is only present since version 0.9.6. If you use an
earlier version, please use the package manager to find out the package
version. For example, `dpkg -l fwupd`.

```shell
$ fwupdmgr get-devices
System Product Name
│
├─8Bitdo SF30 Pro:
│     Device ID:           672c087de09848d9e7ee32aa1dea2fbeb8b81e6b
│     Zusammenfassung:     A redesigned classic game controller
│     Current version:     1.32
│     Vendor:              8Bitdo (USB:0x2DC8)
│     GUIDs:               043c7673-bd45-5e2e-b8b9-c22df2dfec2a
│                          b02f1319-c1c4-54f4-b7f2-5bb3552f6a9e
│                          e95bfb47-11f9-5afd-856e-fbc45730456d
│                          269b3121-097b-50d8-b9ba-d1f64f9cd241
│     Device Flags:        • Updatable
│                          • Supported on remote server
│                          • Requires a bootloader
│                          • Device will not re-appear after update completes
│
[... SSDs, they hopefully didn't cause anything?]
│
└─System Firmware:
      Device ID:           cacb188703e68b1e91250076455571daceb5c0b8
      Current version:     0.0.4101
      Minimum Version:     0.0.4101
      Vendor:              System manufacturer
      GUID:                7645d05e-edbc-539c-8661-b8a82fb53f04
      Device Flags:        • Internal device
                           • Updatable
                           • Requires AC power
                           • Needs a reboot after installation
                           • Cryptographic hash verification is available
                           • Device is usable for the duration of the update
```

Please answer the following questions:

- Operating system and version: Archlinux, Kernel 5.3.8-arch1-1
- How did you install fwupd (ex: `from source`, `pacman`, `apt-get`, etc): pacman
- Have you tried rebooting? not required
- Are you using an NVMe disk? no
- Is secure boot enabled (only for the UEFI plugin)? yes

**Comment by superm1** [comment] 2019-11-04 13:05
Thanks for the feedback!

```
USB error on device 2dc8:5750 : No such device (it may have been disconnected) [-4]
```
I didn't see this myself when doing the various 8bitdo fixups, but it could have been caused by something that landed later.  I'll have to try again.

**Closed** 2019-11-14 14:06 UTC
Labels: bug
