### ISSUE TITLE
Message recipient disconnected from message bus without replying

### ISSUE THREAD

**Issue by minihessel** [fwupd/fwupd#5665] opened 2023-03-30 12:15 UTC
```
[username@hpARCH ~]$ sudo fwupdmgr update -v
(fwupdmgr:3472): GLib-DEBUG: 14:11:09.382: setenv()/putenv() are not thread-safe and should not be used after threads are created
(pkttyagent:3474): GLib-GIO-DEBUG: 14:11:09.386: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(fwupdmgr:3472): GLib-GIO-DEBUG: 14:11:09.395: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: unwatch_fast: "/system/proxy/" (active: 0, establishing: 1)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: unwatch_fast: "/system/proxy/http/" (active: 0, establishing: 1)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: unwatch_fast: "/system/proxy/https/" (active: 0, establishing: 1)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: unwatch_fast: "/system/proxy/ftp/" (active: 0, establishing: 1)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.395: unwatch_fast: "/system/proxy/socks/" (active: 0, establishing: 1)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.397: watch_established: "/system/proxy/" (establishing: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.397: watch_established: "/system/proxy/http/" (establishing: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.397: watch_established: "/system/proxy/https/" (establishing: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.397: watch_established: "/system/proxy/ftp/" (establishing: 0)
(fwupdmgr:3472): dconf-DEBUG: 14:11:09.397: watch_established: "/system/proxy/socks/" (establishing: 0)
(fwupdmgr:3472): GLib-GIO-DEBUG: 14:11:09.400: _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
(fwupdmgr:3472): GLib-GIO-DEBUG: 14:11:09.400: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(fwupdmgr:3472): Fwupd-DEBUG: 14:11:12.864: Emitting ::status-changed() [idle]
Devices with no available firmware updates: 
 • Internal SPI Controller
 • KBG40ZNV256G KIOXIA
 • UEFI Device Firmware
 • UEFI Device Firmware
Devices with the latest available firmware version:
 • Prometheus
(fwupdmgr:3472): FuMain-DEBUG: 14:11:12.873: current version is 10.01.3273255: 10.01.3273255=same
 • Prometheus IOTA Config
(fwupdmgr:3472): FuMain-DEBUG: 14:11:12.876: current version is 0005: 0005=same
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade System Firmware from 0x010b0000 to 0x010c0000?                       ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Fixes and enhancements in System firmware 1.12.0.0:                          ║
║                                                                              ║
║ • Update BIOS to 01.12.00.Refer to hp.com for more details.                  ║
║                                                                              ║
║ HP EliteBook 840 G8 Notebook PC must remain plugged into a power source for  ║
║ the duration of the update to avoid damage.                                  ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: 
Fwupd-INFO: 14:11:14.868: downloading https://fwupd.org/downloads/91250ed646a05e3259ca504fa69a660f8f17087e34e882fb5388018e5ab544a3-T76_01120000.cab
(fwupdmgr:3472): Fwupd-DEBUG: 14:11:14.869: Emitting ::status-changed() [downloading]
Downloading…             [                      \                ]Fwupd-INFO: 14:11:15.740: download progress: 100%
Downloading…             [***************************************]Fwupd-INFO: 14:11:15.814: download progress: 0%
Downloading…             [  -                                    ]Fwupd-INFO: 14:11:15.855: download progress: 1%
Downloading…             [                                       ]Fwupd-INFO: 14:11:15.880: download progress: 2%
Downloading…             [                                       ]Fwupd-INFO: 14:11:15.914: download progress: 3%
Downloading…             [*                                      ]Fwupd-INFO: 14:11:15.939: download progress: 4%
Downloading…             [*                                      ]Fwupd-INFO: 14:11:15.968: download progress: 5%
Downloading…             [*                                      ]Fwupd-INFO: 14:11:15.998: download progress: 6%
Downloading…             [**                                     ]Fwupd-INFO: 14:11:16.026: download progress: 7%
Downloading…             [**                                     ]Fwupd-INFO: 14:11:16.055: download progress: 8%
Downloading…             [***                                    ]Fwupd-INFO: 14:11:16.086: download progress: 9%
Downloading…             [***                                    ]Fwupd-INFO: 14:11:16.113: download progress: 10%
Downloading…             [***                                    ]Fwupd-INFO: 14:11:16.143: download progress: 11%
Downloading…             [****                                   ]Fwupd-INFO: 14:11:16.171: download progress: 12%
Downloading…             [****                                   ]Fwupd-INFO: 14:11:16.201: download progress: 13%
Downloading…             [*****                                  ]Fwupd-INFO: 14:11:16.229: download progress: 14%
Downloading…             [*****                                  ]Fwupd-INFO: 14:11:16.259: download progress: 15%
Downloading…             [*****                                  ]Fwupd-INFO: 14:11:16.290: download progress: 16%
Downloading…             [******                                 ]Fwupd-INFO: 14:11:16.322: download progress: 17%
Downloading…             [******                                 ]Fwupd-INFO: 14:11:16.346: download progress: 18%
Downloading…             [*******                                ]Fwupd-INFO: 14:11:16.379: download progress: 19%
Downloading…             [*******                                ]Fwupd-INFO: 14:11:16.404: download progress: 20%
Downloading…             [*******                                ]Fwupd-INFO: 14:11:16.444: download progress: 21%
Downloading…             [********                               ]Fwupd-INFO: 14:11:16.474: download progress: 22%
Downloading…             [********                               ]Fwupd-INFO: 14:11:16.502: download progress: 23%
Downloading…             [********                               ]Fwupd-INFO: 14:11:16.532: download progress: 24%
Downloading…             [*********                              ]Fwupd-INFO: 14:11:16.563: download progress: 25%
Downloading…             [*********                              ]Fwupd-INFO: 14:11:16.594: download progress: 26%
Downloading…             [**********                             ]Fwupd-INFO: 14:11:16.623: download progress: 27%
Downloading…             [**********                             ]Fwupd-INFO: 14:11:16.649: download progress: 28%
Downloading…             [**********                             ]Fwupd-INFO: 14:11:16.678: download progress: 29%
Downloading…             [***********                            ]Fwupd-INFO: 14:11:16.708: download progress: 30%
Downloading…             [***********                            ]Fwupd-INFO: 14:11:16.737: download progress: 31%
Downloading…             [************                           ]Fwupd-INFO: 14:11:16.767: download progress: 32%
Downloading…             [************                           ]Fwupd-INFO: 14:11:16.801: download progress: 33%
Downloading…             [************                           ]Fwupd-INFO: 14:11:16.832: download progress: 34%
Downloading…             [*************                          ]Fwupd-INFO: 14:11:16.856: download progress: 35%
Downloading…             [*************                          ]Fwupd-INFO: 14:11:16.898: download progress: 36%
Downloading…             [**************                         ]Fwupd-INFO: 14:11:16.920: download progress: 37%
Downloading…             [**************                         ]Fwupd-INFO: 14:11:16.958: download progress: 38%
Downloading…             [**************                         ]Fwupd-INFO: 14:11:16.997: download progress: 39%
Downloading…             [***************                        ]Fwupd-INFO: 14:11:17.033: download progress: 40%
Downloading…             [***************                        ]Fwupd-INFO: 14:11:17.071: download progress: 41%
Downloading…             [***************                        ]Fwupd-INFO: 14:11:17.095: download progress: 42%
Downloading…             [****************                       ]Fwupd-INFO: 14:11:17.119: download progress: 43%
Downloading…             [****************                       ]Fwupd-INFO: 14:11:17.152: download progress: 44%
Downloading…             [*****************                      ]Fwupd-INFO: 14:11:17.194: download progress: 45%
Downloading…             [*****************                      ]Fwupd-INFO: 14:11:17.221: download progress: 46%
Downloading…             [*****************                      ]Fwupd-INFO: 14:11:17.235: download progress: 47%
Downloading…             [******************                     ]Fwupd-INFO: 14:11:17.263: download progress: 48%
Downloading…             [******************                     ]Fwupd-INFO: 14:11:17.287: download progress: 49%
Downloading…             [*******************                    ]Fwupd-INFO: 14:11:17.319: download progress: 50%
Downloading…             [*******************                    ]Fwupd-INFO: 14:11:17.346: download progress: 51%
Downloading…             [*******************                    ]Fwupd-INFO: 14:11:17.358: download progress: 52%
Downloading…             [********************                   ]Fwupd-INFO: 14:11:17.387: download progress: 53%
Downloading…             [********************                   ]Fwupd-INFO: 14:11:17.409: download progress: 54%
Downloading…             [*********************                  ]Fwupd-INFO: 14:11:17.434: download progress: 55%
Downloading…             [*********************                  ]Fwupd-INFO: 14:11:17.447: download progress: 56%
Downloading…             [*********************                  ]Fwupd-INFO: 14:11:17.475: download progress: 57%
Downloading…             [**********************                 ]Fwupd-INFO: 14:11:17.502: download progress: 58%
Downloading…             [**********************                 ]Fwupd-INFO: 14:11:17.509: download progress: 59%
Downloading…             [***********************                ]Fwupd-INFO: 14:11:17.544: download progress: 60%
Downloading…             [***********************                ]Fwupd-INFO: 14:11:17.553: download progress: 61%
Downloading…             [***********************                ]Fwupd-INFO: 14:11:17.566: download progress: 62%
Downloading…             [************************               ]Fwupd-INFO: 14:11:17.578: download progress: 63%
Downloading…             [************************               ]Fwupd-INFO: 14:11:17.589: download progress: 64%
Downloading…             [************************               ]Fwupd-INFO: 14:11:17.600: download progress: 65%
Downloading…             [*************************              ]Fwupd-INFO: 14:11:17.611: download progress: 66%
Downloading…             [*************************              ]Fwupd-INFO: 14:11:17.619: download progress: 67%
Downloading…             [**************************             ]Fwupd-INFO: 14:11:17.636: download progress: 68%
Downloading…             [**************************             ]Fwupd-INFO: 14:11:17.644: download progress: 69%
Downloading…             [**************************             ]Fwupd-INFO: 14:11:17.659: download progress: 70%
Downloading…             [***************************            ]Fwupd-INFO: 14:11:17.667: download progress: 71%
Downloading…             [***************************            ]Fwupd-INFO: 14:11:17.686: download progress: 72%
Downloading…             [****************************           ]Fwupd-INFO: 14:11:17.699: download progress: 73%
Downloading…             [****************************           ]Fwupd-INFO: 14:11:17.711: download progress: 74%
Downloading…             [****************************           ]Fwupd-INFO: 14:11:17.718: download progress: 75%
Downloading…             [*****************************          ]Fwupd-INFO: 14:11:17.738: download progress: 76%
Downloading…             [*****************************          ]Fwupd-INFO: 14:11:17.745: download progress: 77%
Downloading…             [******************************         ]Fwupd-INFO: 14:11:17.763: download progress: 78%
Downloading…             [******************************         ]Fwupd-INFO: 14:11:17.773: download progress: 79%
Downloading…             [******************************         ]Fwupd-INFO: 14:11:17.785: download progress: 80%
Downloading…             [*******************************        ]Fwupd-INFO: 14:11:17.795: download progress: 81%
Downloading…             [*******************************        ]Fwupd-INFO: 14:11:17.805: download progress: 82%
Downloading…             [*******************************        ]Fwupd-INFO: 14:11:17.815: download progress: 83%
Downloading…             [********************************       ]Fwupd-INFO: 14:11:17.827: download progress: 84%
Downloading…             [********************************       ]Fwupd-INFO: 14:11:17.834: download progress: 85%
Downloading…             [*********************************      ]Fwupd-INFO: 14:11:17.843: download progress: 86%
Downloading…             [*********************************      ]Fwupd-INFO: 14:11:17.854: download progress: 87%
Downloading…             [*********************************      ]Fwupd-INFO: 14:11:17.867: download progress: 88%
Downloading…             [**********************************     ]Fwupd-INFO: 14:11:17.876: download progress: 89%
Downloading…             [**********************************     ]Fwupd-INFO: 14:11:17.895: download progress: 90%
Downloading…             [***********************************    ]Fwupd-INFO: 14:11:17.907: download progress: 91%
Downloading…             [***********************************    ]Fwupd-INFO: 14:11:17.919: download progress: 92%
Downloading…             [***********************************    ]Fwupd-INFO: 14:11:17.930: download progress: 93%
Downloading…             [************************************   ]Fwupd-INFO: 14:11:17.943: download progress: 94%
Downloading…             [************************************   ]Fwupd-INFO: 14:11:17.953: download progress: 95%
Downloading…             [*************************************  ]Fwupd-INFO: 14:11:17.966: download progress: 96%
Downloading…             [*************************************  ]Fwupd-INFO: 14:11:17.977: download progress: 97%
Downloading…             [*************************************  ]Fwupd-INFO: 14:11:17.986: download progress: 98%
Downloading…             [************************************** ]Fwupd-INFO: 14:11:17.996: download progress: 99%
Downloading…             [************************************** ]Fwupd-INFO: 14:11:18.006: download progress: 100%
(fwupdmgr:3472): Fwupd-DEBUG: 14:11:18.006: Emitting ::status-changed() [idle]
Fwupd-INFO: 14:11:18.006: status-code was 200
(fwupdmgr:3472): Fwupd-DEBUG: 14:11:18.157: Emitting ::status-changed() [decompressing]
Decompressing…           [***************************************](fwupdmgr:3472): Fwupd-DEBUG: 14:11:18.820: Emitting ::device-changed(a45df35ac0e948ee180fe216a5f703f32dda163f)
(fwupdmgr:3472): Fwupd-DEBUG: 14:11:18.820: Emitting ::status-changed() [waiting-for-auth]
Authenticating…          [***************************************]
Message recipient disconnected from message bus without replying

```

**Comment by hughsie** [comment] 2023-03-30 12:19
Dupe of https://github.com/fwupd/fwupd/issues/5656

**Closed by hughsie** 2023-03-30 12:19 UTC
