### ISSUE TITLE
fwupd for thunderbolt 3 controller on lenovo X1 gen 3 fails with version mismatch error

### ISSUE THREAD

**Issue by DanielJoyce** [fwupd/fwupd#3960] opened 2021-11-05 22:18 UTC
**Describe the bug**

Pop_OS 21.04 says there was a new release for this firmware. Tried to install it from the graphical installer, fails with 

`Firmware version formats were different, device was 'pair' and release is 'plain'`

From terminal:

```
❯ fwupdmgr update --verbose
(fwupdmgr:1094245): GLib-DEBUG: 15:05:44.983: setenv()/putenv() are not thread-safe and should not be used after threads are created
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:44.993: Emitting ::status-changed() [idle]
Devices with no available firmware updates: 
 • Integrated Camera
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI dbx
Upgrade available for Thunderbolt host controller from 59.00 to 62.00
Thunderbolt host controller and all connected devices may not be usable while updating. Continue with update? [Y|n]: Y
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.592: downloading https://fwupd.org/downloads/7e33d51c7bc2124e21569b46775be893ea7d1f6f6a67460b7d1cd0a93d843ccd-Lenovo-ThinkPad-X1E-Gen-3rd-Thunderbolt-Firmware-N2VTG08W-Secured.cab
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.592: Emitting ::status-changed() [downloading]
Downloading…             [ -                                     ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.828: download progress: 2%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.829: download progress: 2%
Downloading…             [                                       ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.848: download progress: 8%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.848: download progress: 8%
Downloading…             [***                                    ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.881: download progress: 22%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.881: download progress: 22%
Downloading…             [********                               ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.907: download progress: 29%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.907: download progress: 29%
Downloading…             [***********                            ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.909: download progress: 37%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.909: download progress: 37%
Downloading…             [**************                         ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.945: download progress: 44%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.945: download progress: 44%
Downloading…             [*****************                      ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.946: download progress: 59%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.947: download progress: 59%
Downloading…             [***********************                ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.969: download progress: 74%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.969: download progress: 74%
Downloading…             [****************************           ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.976: download progress: 89%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.976: download progress: 89%
Downloading…             [**********************************     ](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.979: download progress: 100%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.979: download progress: 100%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.979: download progress: 100%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.979: download progress: 100%
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.979: Emitting ::status-changed() [idle]
Downloading…             [***************************************]
(fwupdmgr:1094245): Fwupd-DEBUG: 15:05:47.984: Emitting ::status-changed() [decompressing]
Decompressing…           [***************************************](fwupdmgr:1094245): Fwupd-DEBUG: 15:05:48.010: Emitting ::status-changed() [idle]
Decompressing…           [***************************************]
Firmware version formats were different, device was 'pair' and release is 'plain'

~ took 3s 

```

**Steps to Reproduce**

`fwupdmgr update --verbose`

**Expected behavior**
Firmware update for thunderbolt controller should succeed

**fwupd version information**
Please provide the version of the daemon and client.

```shell
fwupdmgr --version

❯ fwupdmgr --version
client version:	1.5.11
compile-time dependency versions
	gusb:	0.3.5

daemon version:	1.5.11

```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):

Came pre-installed

**fwupd device information**
Please provide the output of the fwupd devices recognized in your system.

```shell
❯ fwupdmgr get-devices --show-all-devices
20TKCTO1WW
│
├─Thunderbolt host controller:
│     Device ID:          f00bd888a7a6462efd768dbcd7b7cf57474b941a
│     Summary:            Unmatched performance for high-speed I/O
│     Current version:    59.00
│     Vendor:             Lenovo (THUNDERBOLT:0x0109, TBT:0x0109)
│     GUIDs:              ee645d33-1554-5eee-9cb3-ad2a36b1c250
│                         d1937626-567e-5753-a45b-9af54b8e1a0b
│                         0c42d35e-20c9-5c9b-9fc2-9d596a7f1c9e
│                         66f32039-10c2-5be5-90dc-123e0648f99a
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Device stages updates
│   
├─Embedded Controller:
│     Device ID:          6d9eb6430db8e288b0287036bbb254bf92aa52c6
│     Current version:    0.1.8
│     Minimum Version:    0.1.8
│     Vendor:             DMI:LENOVO
│     GUIDs:              b616d3d6-cca9-40bd-964e-b86ffb62744d
│                         56ee8ee1-8935-5d75-9ede-2ab1422d642e
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Integrated Camera:
│     Device ID:          0fef0a0c55f6442bffaebd774ae771341c89571b
│     Current version:    60.1
│     Vendor:             Azurewave (USB:0x13D3)
│     GUIDs:              4dc71255-84a9-5adc-8eab-c5982db48621
│                         9284c551-0b4c-51ee-905a-168b8787290c
│     Device Flags:       • Updatable
│   
├─Intel Management Engine:
│     Device ID:          e17ca6a5faa5785d027c8803e53aedcdadbaf325
│     Current version:    225.53.1649
│     Minimum Version:    0.0.1
│     Vendor:             DMI:LENOVO
│     GUIDs:              5695cc48-4f4f-4677-8ffb-9f496d3ad9d3
│                         3ef35d3b-ceeb-5e27-8c0a-ac25f90367ab
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel(R) Core™ i7-10850H CPU @ 2.70GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000ea
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f
│                         30249f37-d140-5d3e-9319-186b1bd5cac3
│                         a45b0522-5722-54bd-b802-86cd044262df
│                         7b9b6e8c-226c-5db6-86cb-ea3187578013
│     Device Flags:       • Internal device
│   
├─SKHynix HFS001TD9TNI-L2B0B:
│     Device ID:          08e1798bf5d9cb56a0290b552cab6c1a371b5089
│     Summary:            NVM Express Solid State Drive
│     Current version:    11720C10
│     Vendor:             SK hynix (NVME:0x1C5C)
│     GUIDs:              424e8633-6c06-5c41-bd78-fbcb483dc0fb
│                         b7603cf7-873e-59e8-b7aa-9d8a9877b6e7
│                         af90743d-93b0-5a7f-b3aa-08db33ab1f82
│                         85ef24c5-fc0a-57a6-ab37-5711ac8acfbb
│                         06f40517-864f-57be-9dad-d48bec1667e0
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          da99ffa7e037e614f6f43e730e9aedba0a603152
│ │   Current version:    0.1.18
│ │   Minimum Version:    0.1.0
│ │   Vendor:             LENOVO (DMI:LENOVO)
│ │   GUIDs:              6e58e73d-8061-44e4-8949-33b7f0d5c726
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       0e91d507-ea0c-5543-9850-204d9a6635c7
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ ├─Intel AMT [unprovisioned]:
│ │     Device ID:        e2623122c99d58220498aacbfcfdb1baebbae3c5
│ │     Summary:          Hardware and firmware technology for remote out-of-band management
│ │     Current version:  14.1.53.1649
│ │     Bootloader Version:14.1.53.1649
│ │     Vendor:           Intel Corporation
│ │     GUID:             2800f812-b7b4-2d4b-aca8-46e0ff65814c
│ │     Device Flags:     • Internal device
│ │   
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI Revocation Database
│       Current version:  83
│       Minimum Version:  83
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            14503b3d-73ce-5d06-8137-77c68972a341
│                         5971a208-da00-5fce-b5f5-1234342f9cf7
│                         c6682ade-b5ec-57c4-b687-676351208742
│                         f8ba2887-9411-5c36-9cee-88995bb39731
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│     
├─TPM:
│ │   Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│ │   Current version:    1.258.0.0
│ │   Vendor:             ST Microelectronics (TPM:STM)
│ │   GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6
│ │                       84df3581-f896-54d2-bd1a-372602f04c32
│ │                       bfaed10a-bbc1-525b-a329-35da2f63e918
│ │                       70b7b833-7e1a-550a-a291-b94a12d0f319
│ │                       06f005e9-cb62-5d1a-82d9-13c534c53c48
│ │   Device Flags:       • Internal device
│ │ 
│ └─Event Log:
│       Device ID:        58bd405f31c48e6eca290b425f530a94c91e955c
│       GUID:             a25657fe-b5dc-5be0-8b78-8b9dfec678ff
│       Device Flags:     • Internal device
│     
├─TU117M [GeForce GTX 1650 Ti Mobile]:
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a1
│     Vendor:             NVIDIA Corporation (PCI:0x10DE)
│     GUIDs:              1b288f6e-78bb-5727-a9cf-2a6daf45b7c9
│                         0c679cdc-10fb-56af-9883-90dfa34d1a5d
│                         e8982b3b-d8c4-5f23-af8e-33999c0e8026
│                         6eec15ed-752e-5418-99ae-3171b61091ef
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─UEFI Device Firmware:
│     Device ID:          dbea39b96e61b7b1bc31f03e8b0530935b3989bb
│     Current version:    16777222
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     GUIDs:              439d54f4-5548-4698-a8b0-46a047c0e66e
│                         5b1a70bd-0c00-56c1-9a9e-d54fe2072ce1
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          aaa9b84f8cf13c5db4bbc894a23240288b663514
│     Current version:    65794
│     Minimum Version:    65794
│     Vendor:             DMI:LENOVO
│     GUIDs:              3fb9a55d-d7f1-4d1b-b216-74e328e28f51
│                         fa397613-68af-5c18-aea0-012f7bd9cc97
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
└─UEFI Device Firmware:
      Device ID:          f6298ecf39842bc3399a308b5d95169b3cab3de5
      Current version:    24577
      Minimum Version:    1
      Vendor:             DMI:LENOVO
      GUIDs:              33967546-da89-4c51-9c95-5242bcb854e8
                          79caa862-d124-5315-8b86-f79e0d0774b9
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
    
________________________________________________

Devices that have been updated successfully:

 • Embedded Controller (0.1.6 → 0.1.08)
 • System Firmware (0.1.11 → 0.1.18)
 • SKHynix HFS001TD9TNI-L2B0B (11710C10 → 11720C10)
 • Intel Management Engine (224.36.1158 → 225.53.1649)
```

**Additional questions**

- Operating system and version:

```
❯ cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Pop!_OS 21.04"

❯ uname -a
Linux phylum-1 5.13.0-7614-generic #14~1631647151~21.04~930e87c-Ubuntu SMP Fri Sep 17 00:24:58 UTC  x86_64 x86_64 x86_64 GNU/Linux

```

- Have you tried rebooting?

Yes 

- Is this a regression?

First time updating firmware

**Comment by hughsie** [comment] 2021-11-06 20:37
Dupe of https://github.com/fwupd/firmware-lenovo-thinkpad/issues/166 I'm afraid.

**Closed by hughsie** 2021-11-06 20:37 UTC
Labels: bug
