### ISSUE TITLE
TPM PCR0 differs from reconstruction

### ISSUE THREAD

**Issue by johnjacob10** [fwupd/fwupd#2361] opened 2020-09-08 17:11 UTC
I have a Dell XPS 9300 running Ubuntu 20.04, and I get the above message in gnome-firmware. As per the wiki at https://github.com/fwupd/fwupd/wiki/TPM-PCR0-differs-from-reconstruction , could you help me interpret and fix this?

The output from fwupdtpmevlog is attached.

Thanks in advance!

[fwupdtpmevlog.txt](https://github.com/fwupd/fwupd/files/5189851/fwupdtpmevlog.txt)

**Comment by superm1** [comment] 2020-09-08 18:03
duplicate of https://github.com/fwupd/fwupd/issues/2361

**Closed by superm1** 2020-09-08 18:03 UTC
