### ISSUE TITLE
Dell WD19 upgrade issue

### ISSUE THREAD

**Issue by fredoche** [fwupd/fwupd#2956] opened 2021-03-01 09:45 UTC
**Describe the bug**
I cannot update to the latest firmware version. gnome-software, the stand-alone  "firmware" program, and CLI fwupdmgr all prompt for an update. When told to proceed, they look like they are performing the update, yet, the firmware on the WD19TB stays the same (TB ver 43 instead of 60).
yet,
when running wupdmgr get-devices --filter=~internal , it says that the devices have been updated successfully, which may, or may not, get your analytics maybe off place.
``` Devices that have been updated successfully:

 • VMM5331 in Dell dock (05.04.03 → 05.04.06)
 • WD19TB (01.00.00.04 → 01.00.00.05)
 • Package level of Dell dock (01.00.15.00 → 01.00.15.01)
 • Thunderbolt controller in Dell dock (43.00 → 60.00)
```

**Steps to Reproduce**
run fwupdmgr twice in a row.
```
root@grey-matter fred]# fwupdmgr  update
Devices with no available firmware updates: 
 • Thunderbolt host controller
Upgrade available for Thunderbolt controller in Dell dock from 43.00 to 60.00
Thunderbolt controller in Dell dock must remain connected for the duration of the update to avoid damage. Continue with update? [Y|n]: y
Téléchargement…          [***************************************]
Décompression…           [***************************************]
Authentification…        [***************************************]
Authentification…        [***************************************]
Mise à jour de Thunderbolt controller in Dell dock…**************]
Écriture…                [***************************************]
Successfully installed firmware
Devices with the latest available firmware version:
 • Package level of Dell dock
 • RTS5413 in Dell dock
 • RTS5487 in Dell dock
 • VMM5331 in Dell dock
 • WD19TB
 • Micron 2200S NVMe 512GB
 • UEFI dbx
[root@grey-matter fred]# fwupdmgr  update
Devices with no available firmware updates: 
 • Thunderbolt host controller
Upgrade available for Thunderbolt controller in Dell dock from 43.00 to 60.00
Thunderbolt controller in Dell dock must remain connected for the duration of the update to avoid damage. Continue with update? [Y|n]:
```

**Expected behavior**
the second fwupmgr should be no-op , and the firmware should show as updated.

**fwupd version information**
Please provide the version of the daemon and client.
```shell
$ fwupdmgr --version
[root@grey-matter fred]# fwupdmgr --version
client version:	1.5.7
compile-time dependency versions
	gusb:	0.3.5

daemon version:	1.5.7

```

Please note how you installed it (`apt`, `dnf`, `pacman`, source, etc):
Fedora 33 default, so dnf I guess

**fwupd device information**
Please provide the output of the external fwupd devices recognized in your system.

```shell
fwupdmgr get-devices --filter=~internal
XPS 13 7390
│
└─WD19TB:
  │   Device ID:          570867f4ddda9915445da59bd85cd0e0e507270e
  │   Résumé:             High performance dock
  │   Version actuelle:   01.00.00.05
  │   Version minimum:    01.00.00.00
  │   Fournisseur:        Dell Inc. (USB:0x413C)
  │   Install Duration:   1 minute
  │   Serial Number:      JKM4523/3156728074480562
  │   GUID:               cd357cf1-40b2-5d87-b8df-bb2dd82774aa ← USB\VID_413C&PID_B06E&hub&embedded
  │   Device Flags:       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Device stages updates
  │                       • Device can recover flash failures
  │                       • Device is usable for the duration of the update
  │ 
  ├─Thunderbolt controller in Dell dock:
  │     Device ID:        a32b64cc7533b072183b9a78f2a326679c89d948
  │     Résumé:           Thunderbolt controller
  │     Version actuelle: 43.00
  │     Fournisseur:      Dell Inc. (THUNDERBOLT:0x00D4|TBT:0x00D4)
  │     Install Duration: 22 secondes
  │     Update State:     Success
  │     Last modified:    2021-03-01 09:32
  │     GUIDs:            48711a14-0aaa-55b8-a17f-f7c494b318c6 ← THUNDERBOLT\VEN_00D4&DEV_B070&REV_00
  │                       08a8c886-2818-544c-b1a3-588eb07ae487 ← THUNDERBOLT\VEN_00D4&DEV_B070
  │                       c94770ca-1773-592c-b20a-e87243bc7cd0 ← TBT-00d4b070
  │     Device Flags:     • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Install to parent device first
  │                       • Device update needs activation
  │                       • Device stages updates
  │                       • Device is usable for the duration of the update
  │   
  ├─Package level of Dell dock:
  │     Device ID:        073624c16dd99abe01ba1da223a70321e4f29beb
  │     Résumé:           A representation of dock update status
  │     Version actuelle: 01.00.15.01
  │     Fournisseur:      Dell Inc. (USB:0x413C)
  │     Install Duration: 5 secondes
  │     Update State:     Success
  │     Last modified:    2021-03-01 09:25
  │     GUID:             8ceeeffd-51b6-580c-9b75-69143227aff8 ← USB\VID_413C&PID_B06E&hub&status
  │     Device Flags:     • Updatable
  │                       • Supported on remote server
  │                       • Device can recover flash failures
  │                       • Device is usable for the duration of the update
  │   
  ├─RTS5413 in Dell dock:
  │     Device ID:        0acceea54e71c4d8002593822afe0f4705616613
  │     Résumé:           USB 3.1 Generation 1 Hub
  │     Version actuelle: 01.21
  │     Fournisseur:      Dell Inc. (USB:0x413C)
  │     Install Duration: 14 secondes
  │     GUIDs:            86fb40c0-8bf5-5a8b-a4ad-3156cf6bfaf4 ← USB\VID_413C&PID_B06F&REV_0101
  │                       b27d25f1-019d-5718-b41a-02ddaefe5577 ← USB\VID_413C&PID_B06F
  │                       ac5b774c-b49d-566b-9255-85f0f7f8a4ed ← USB\VID_413C&PID_B06F&hub
  │     Device Flags:     • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Device stages updates
  │                       • Device is usable for the duration of the update
  │   
  ├─RTS5487 in Dell dock:
  │     Device ID:        96969b82d977fdcbf607df084ef0dcf10119409b
  │     Résumé:           USB 3.1 Generation 2 Hub
  │     Version actuelle: 01.47
  │     Fournisseur:      Dell Inc. (USB:0x413C)
  │     Install Duration: 3 secondes
  │     GUIDs:            707c63d2-e597-5c40-84db-9b1bb4c48d96 ← USB\VID_413C&PID_B06E&REV_0101
  │                       acfcd89b-105d-55b9-b85b-08bf8508f38c ← USB\VID_413C&PID_B06E
  │                       568ffa1e-a0db-5287-9ea3-872b60f7730b ← USB\VID_413C&PID_B06E&hub
  │     Device Flags:     • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Device stages updates
  │                       • Device is usable for the duration of the update
  │   
  └─VMM5331 in Dell dock:
        Device ID:        228ac6846b64d532dd1ea1b7e651e8f5f55fbc34
        Résumé:           Multi Stream Transport controller
        Version actuelle: 05.04.06
        Fournisseur:      Dell Inc. (USB:0x413C)
        Install Duration: 6 minutes
        GUID:             89fec0b6-6b76-5008-b82c-5e5c6c164007 ← MST-panamera-vmm5331-259
        Device Flags:     • Updatable
                          • System requires external power source
                          • Supported on remote server
                          • Device stages updates
                          • Device is usable for the duration of the update
      
________________________________________________

Devices that have been updated successfully:

 • VMM5331 in Dell dock (05.04.03 → 05.04.06)
 • WD19TB (01.00.00.04 → 01.00.00.05)
 • Package level of Dell dock (01.00.15.00 → 01.00.15.01)
 • Thunderbolt controller in Dell dock (43.00 → 60.00)

Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection):
0.	Do not upload reports at this time, but prompt again for future updates
1.	Do not upload reports, and never ask to upload reports for future updates
2.	Upload reports just this one time, but prompt again for future updates
3.	Upload reports this time and automatically upload reports after completing future updates

```

**Dock SKU**
Please mention which module is installed in your WD19.

- [ ] WD19 (Single-C)
- [x] WD19TB (Thunderbolt)
- [ ] WD19DC (Dual-C)

**Peripherals connected to the dock**
Please describe all devices connected to the dock.  Be as specific as possible,
including USB devices, hubs, monitors, and downstream type-C devices.
ethernet cable 1gb, corsair k65 keyboard, logitech mouse g900, samsung chg70 via hdmi. I unplugged them all at some point to test the update, but it made no visible difference.

**Verbose daemon logs**
First enable daemon verbose logs collection.
```shell
fwupdmgr modify-config "VerboseDomains" "*"
```

Then try to reproduce the issue.  Even if it doesn't reproduce, please attach the
daemon verbose logs collected from the system journal.
```shell
[root@grey-matter fred]# journalctl -b -u fwupd.service
-- Logs begin at Thu 2020-03-26 19:54:39 CET, end at Mon 2021-03-01 10:44:16 CET. --
mars 01 10:23:38 grey-matter systemd[1]: Starting Firmware update daemon...
mars 01 10:23:42 grey-matter fwupd[3010]: 09:23:42:0387 FuEngine             failed to add device (null): failed get ffu_capable for (null)
mars 01 10:23:43 grey-matter systemd[1]: Started Firmware update daemon.
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             loading config values from /etc/fwupd/daemon.conf
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             using autodetected max archive size 18,4 Eo
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 GLib                 setenv()/putenv() are not thread-safe and should not be used after t>
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             ::configuration changed
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuIdle               setting timeout to 7200s
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             loading config values from /etc/fwupd/daemon.conf
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             using autodetected max archive size 18,4 Eo
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 GLib                 setenv()/putenv() are not thread-safe and should not be used after t>
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             ::configuration changed
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuIdle               setting timeout to 7200s
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             loading config values from /etc/fwupd/daemon.conf
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             using autodetected max archive size 18,4 Eo
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 GLib                 setenv()/putenv() are not thread-safe and should not be used after t>
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             ::configuration changed
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuIdle               setting timeout to 7200s
mars 01 10:42:14 grey-matter systemd[1]: Stopping Firmware update daemon...
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(synaptics_mst)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(logind)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(upower)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(modem_manager)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0968 FuPlugin             destroy(linux_lockdown)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0968 FuPlugin             destroy(tpm_eventlog)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(linux_swap)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(dell)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(flashrom)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(linux_tainted)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0970 FuPlugin             destroy(redfish)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0970 FuPlugin             destroy(uefi_capsule)
mars 01 10:42:14 grey-matter systemd[1]: fwupd.service: Succeeded.
mars 01 10:42:14 grey-matter systemd[1]: Stopped Firmware update daemon.
mars 01 10:42:24 grey-matter systemd[1]: Starting Firmware update daemon...
mars 01 10:42:24 grey-matter fwupd[5358]: 09:42:24:0617 FuRemoteList         loading /usr/share/fwupd/metainfo
mars 01 10:42:24 grey-matter fwupd[5358]: 09:42:24:0617 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb
[root@grey-matter fred]# 
[root@grey-matter fred]# 
[root@grey-matter fred]# 
[root@grey-matter fred]# 
[root@grey-matter fred]# 
[root@grey-matter fred]# journalctl -b -u fwupd.service
-- Logs begin at Thu 2020-03-26 19:54:39 CET, end at Mon 2021-03-01 10:44:16 CET. --
mars 01 10:23:38 grey-matter systemd[1]: Starting Firmware update daemon...
mars 01 10:23:42 grey-matter fwupd[3010]: 09:23:42:0387 FuEngine             failed to add device (null): failed get ffu_capable for (null)
mars 01 10:23:43 grey-matter systemd[1]: Started Firmware update daemon.
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             loading config values from /etc/fwupd/daemon.conf
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             using autodetected max archive size 18,4 Eo
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 GLib                 setenv()/putenv() are not thread-safe and should not be used after t>
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             ::configuration changed
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuIdle               setting timeout to 7200s
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0841 FuConfig             loading config values from /etc/fwupd/daemon.conf
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             using autodetected max archive size 18,4 Eo
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 GLib                 setenv()/putenv() are not thread-safe and should not be used after t>
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             ::configuration changed
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuIdle               setting timeout to 7200s
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             /etc/fwupd/daemon.conf changed, reloading all configs
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             loading config values from /etc/fwupd/daemon.conf
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             using autodetected max archive size 18,4 Eo
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 GLib                 setenv()/putenv() are not thread-safe and should not be used after t>
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuConfig             ::configuration changed
mars 01 10:42:12 grey-matter fwupd[3010]: 09:42:12:0842 FuIdle               setting timeout to 7200s
mars 01 10:42:14 grey-matter systemd[1]: Stopping Firmware update daemon...
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(synaptics_mst)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(logind)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(upower)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0965 FuPlugin             destroy(modem_manager)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0968 FuPlugin             destroy(linux_lockdown)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0968 FuPlugin             destroy(tpm_eventlog)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(linux_swap)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(dell)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(flashrom)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0969 FuPlugin             destroy(linux_tainted)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0970 FuPlugin             destroy(redfish)
mars 01 10:42:14 grey-matter fwupd[3010]: 09:42:14:0970 FuPlugin             destroy(uefi_capsule)
mars 01 10:42:14 grey-matter systemd[1]: fwupd.service: Succeeded.
mars 01 10:42:14 grey-matter systemd[1]: Stopped Firmware update daemon.
mars 01 10:42:24 grey-matter systemd[1]: Starting Firmware update daemon...
mars 01 10:42:24 grey-matter fwupd[5358]: 09:42:24:0617 FuRemoteList         loading /usr/share/fwupd/metainfo
mars 01 10:42:24 grey-matter fwupd[5358]: 09:42:24:0617 XbSilo               attempting to load /var/cache/fwupd/metainfo.xmlb

```

**Additional questions**
- Operating system and version: fedora 33 workstation
- Have you tried unplugging the dock or any peripherals from your machine? yes
- Have you tried to power cycle the dock from the AC adapter? yes
- Is this a regression? I dont know

**Comment by fredoche** [comment] 2021-03-01 09:47
For the record, after writing this report, so , for like 5 minutes, after changing the log level, while every peripheral (eth, usb, hdmi) disconnected, now, "fwupdmgr  update" doesnt prompt for the same update. I'll check now if the update has been applied correctly after reboot and a/c disconnect and will let you know

**Comment by fredoche** [comment] 2021-03-01 09:52
Aaand its updated! So some patience is required. Maybe mashing the update button kind of start the update all over again, maybe I got unlucky, maybe the announced duration (22 seconds) for update is kind of optimistic, maybe the device got scared when I reached out for help on github, I really can't tell. In any case my firmware is updated, maybe I fell into an unfortunate UX issue or just got plain unlucky. Thanks, keep up the good work

**Comment by superm1** [comment] 2021-03-01 14:32
Well glad it got done, but let's find out what happened..

When it "wasn't working", did you happen to unplug the dock in-between attempts?  And if you did - did you unplug from host or from wall AC adapter?

The flow is _supposed_ to be:
1. `fwupdmgr update`
2. You get a message telling you the update finishes next time you unplug dock from host
3. You unplug dock from host
4. Plug dock back in
4. Fully updated

**Comment by superm1** [comment] 2021-03-01 15:20
@hughsie did the update message get lost in the metadata again?  There was a new release just pushed out yesterday that @fredoche has run here, I wonder if it's missing.

**Comment by hughsie** [comment] 2021-03-01 16:14
> did the update message get lost in the metadata again

Looks okay here.

**Comment by superm1** [comment] 2021-03-01 21:51
> Looks okay here.

I fetched the stable metadata, and yeah I see it in the EC as well.
![image](https://user-images.githubusercontent.com/494526/109563232-1c6c8a80-7aa5-11eb-9eb3-279e27d7a07c.png)

BTW I noticed this in requires, not sure how that is happening in stable, nor how it was possible for @fredoche to update with this here.
```
    <requires>
      <firmware compare="eq" version="XXX:NEVER_GOING_TO_MATCH">vendor-id</firmware>
    </requires>
```

>and I dont believe gnome-software or firmware told me either

Gnome-software doesn't do anything with it _currently_:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/806

>flow
```
Successfully installed firmware
Devices with the latest available firmware version:
 • Package level of Dell dock
 • RTS5413 in Dell dock
 • RTS5487 in Dell dock
 • VMM5331 in Dell dock
 • WD19TB
 • Micron 2200S NVMe 512GB
 • UEFI dbx
[root@grey-matter fred]# fwupdmgr  update
Devices with no available firmware updates: 
 • Thunderbolt host controller
Upgrade available for Thunderbolt controller in Dell dock from 43.00 to 60.00
Thunderbolt controller in Dell dock must remain connected for the duration of the update to avoid damage. Continue with update? [Y|n]:
```
@hughsie  I wonder if we're missing removing the updatable flag or lying about the version.  I _think_ what happened is device is in needs-activation right now but version number doesn't update so it still looks like it needs an update.
Which approach is better in your mind?

**Comment by superm1** [comment] 2021-03-01 22:06
>       <firmware compare="eq" version="XXX:NEVER_GOING_TO_MATCH">vendor-id</firmware>

The number of downloads is also really low, so I worry about this.

**Comment by hughsie** [comment] 2021-03-01 22:11
What's the vendor ID supposed to be?

**Comment by superm1** [comment] 2021-03-01 22:14
Everything but the TBT controller: `USB:0x413C`.  TBT controller either of : `THUNDERBOLT:0x00D4|TBT:0x00D4`

**Comment by hughsie** [comment] 2021-03-02 12:39
> Everything but the TBT controller: USB:0x413C. TBT controller either of : THUNDERBOLT:0x00D4|TBT:0x00D4

The `dell` account has all those already. Remember it's the uploader ODM that needs the vendor-id set; I've assigned the ODM the requried USB vendor ID.

**Comment by superm1** [comment] 2021-03-05 13:42
As mentioned above this is caused by fwupd leaving the device in `updatable` state but also not bumping the version. 
This behavior is fixed by https://github.com/fwupd/fwupd/commit/3df7dd370888b49670e374f8c213f35430ad7b42 which will be in fwupd 1.5.8.  On any earlier version of fwupd, if you simply call `fwupdtool activate` or unplug the USB-C cable then it will complete the update.

**Closed by superm1** 2021-03-05 13:42 UTC
Labels: bug
