### ISSUE TITLE
Wrong vendor shown for SSD

### ISSUE THREAD

**Issue by paulmenzel** [fwupd/fwupd#1673] opened 2019-12-26 15:23 UTC
```
$ fwupdmgr --version
client version: 1.3.5-615-g7fb6cbc5
compile-time dependency versions
        gusb:   0.3.0
        efivar: 37
daemon version: 1.3.5-615-g7fb6cbc5
$ fwupdmgr get-devices
MS-7A37
│
└─CT1000MX500SSD4:
      Device ID:           bf97ef88a4eda3055c079a95e0636fe2887d5436
      Zusammenfassung:     ATA Drive
      Current version:     M3CR020
      Vendor:              Advanced Micro Devices, Inc. [AMD]
      GUIDs:               7fe72eb9-09fe-510e-a062-eb07f185035b
                           1d4f3437-add2-559d-bd88-0a10880e59d3
                           49811b52-642d-5307-bc6f-32e2033fb26a
      Device Flags:        • Internal device
                           • Updatable
                           • Requires AC power
                           • Needs a reboot after installation
                           • Device is usable for the duration of the update

```

The SSD is manufactured by *Crucial* and not *AMD*.

**Comment by superm1** [comment] 2020-01-06 15:38
This should be fixed now in master since #1679 was merged.  If you reproduce it with current master (or 1.3.7+ when released), please reopen.

**Closed by superm1** 2020-01-06 15:38 UTC
